<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lyubov Doroshenko">
<meta name="dcterms.date" content="2026-09-23">

<title>Fisheries Aggregation Shiny App</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="fisheries_documentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="fisheries_documentation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="fisheries_documentation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="fisheries_documentation_files/libs/quarto-html/popper.min.js"></script>
<script src="fisheries_documentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="fisheries_documentation_files/libs/quarto-html/anchor.min.js"></script>
<link href="fisheries_documentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="fisheries_documentation_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="fisheries_documentation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="fisheries_documentation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="fisheries_documentation_files/libs/bootstrap/bootstrap-8872178e3d44aeba0b26a99db51cb85f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<script src="fisheries_documentation_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="fisheries_documentation_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="fisheries_documentation_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#document-purpose" id="toc-document-purpose" class="nav-link active" data-scroll-target="#document-purpose"><span class="header-section-number">1</span> Document purpose</a></li>
  <li><a href="#application-overview" id="toc-application-overview" class="nav-link" data-scroll-target="#application-overview"><span class="header-section-number">2</span> Application overview</a>
  <ul>
  <li><a href="#main-objective" id="toc-main-objective" class="nav-link" data-scroll-target="#main-objective"><span class="header-section-number">2.1</span> Main objective</a></li>
  <li><a href="#conceptual-workflow" id="toc-conceptual-workflow" class="nav-link" data-scroll-target="#conceptual-workflow"><span class="header-section-number">2.2</span> Conceptual workflow</a></li>
  <li><a href="#separation-between-filtering-and-aggregation" id="toc-separation-between-filtering-and-aggregation" class="nav-link" data-scroll-target="#separation-between-filtering-and-aggregation"><span class="header-section-number">2.3</span> Separation between filtering and aggregation</a></li>
  </ul></li>
  <li><a href="#application-architecture" id="toc-application-architecture" class="nav-link" data-scroll-target="#application-architecture"><span class="header-section-number">3</span> Application architecture</a></li>
  <li><a href="#supported-datasets" id="toc-supported-datasets" class="nav-link" data-scroll-target="#supported-datasets"><span class="header-section-number">4</span> Supported datasets</a>
  <ul>
  <li><a href="#dataset-registry" id="toc-dataset-registry" class="nav-link" data-scroll-target="#dataset-registry"><span class="header-section-number">4.1</span> Dataset registry</a></li>
  <li><a href="#dataset-groups" id="toc-dataset-groups" class="nav-link" data-scroll-target="#dataset-groups"><span class="header-section-number">4.2</span> Dataset groups</a></li>
  </ul></li>
  <li><a href="#dataset-structure" id="toc-dataset-structure" class="nav-link" data-scroll-target="#dataset-structure"><span class="header-section-number">5</span> Dataset structure</a>
  <ul>
  <li><a href="#common-columns" id="toc-common-columns" class="nav-link" data-scroll-target="#common-columns"><span class="header-section-number">5.1</span> Common columns</a></li>
  <li><a href="#optional-columns" id="toc-optional-columns" class="nav-link" data-scroll-target="#optional-columns"><span class="header-section-number">5.2</span> Optional columns</a></li>
  </ul></li>
  <li><a href="#data-loading-and-preprocessing" id="toc-data-loading-and-preprocessing" class="nav-link" data-scroll-target="#data-loading-and-preprocessing"><span class="header-section-number">6</span> Data loading and preprocessing</a>
  <ul>
  <li><a href="#client-initialization-and-dataset-loading" id="toc-client-initialization-and-dataset-loading" class="nav-link" data-scroll-target="#client-initialization-and-dataset-loading"><span class="header-section-number">6.1</span> Client initialization and dataset loading</a></li>
  <li><a href="#dataset-summary" id="toc-dataset-summary" class="nav-link" data-scroll-target="#dataset-summary"><span class="header-section-number">6.2</span> Dataset summary</a></li>
  </ul></li>
  <li><a href="#filtering-methodology" id="toc-filtering-methodology" class="nav-link" data-scroll-target="#filtering-methodology"><span class="header-section-number">7</span> Filtering methodology</a>
  <ul>
  <li><a href="#general-rule" id="toc-general-rule" class="nav-link" data-scroll-target="#general-rule"><span class="header-section-number">7.1</span> General rule</a></li>
  <li><a href="#year-filter" id="toc-year-filter" class="nav-link" data-scroll-target="#year-filter"><span class="header-section-number">7.2</span> Year filter</a></li>
  <li><a href="#measured-element-filter" id="toc-measured-element-filter" class="nav-link" data-scroll-target="#measured-element-filter"><span class="header-section-number">7.3</span> Measured-element filter</a></li>
  <li><a href="#hierarchical-filters" id="toc-hierarchical-filters" class="nav-link" data-scroll-target="#hierarchical-filters"><span class="header-section-number">7.4</span> Hierarchical filters</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">7.4.1</span> Example</a></li>
  </ul></li>
  <li><a href="#most-specific-filter-selection-rule" id="toc-most-specific-filter-selection-rule" class="nav-link" data-scroll-target="#most-specific-filter-selection-rule"><span class="header-section-number">7.5</span> Most-specific filter-selection rule</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span class="header-section-number">7.5.1</span> Example</a></li>
  </ul></li>
  <li><a href="#flat-filters" id="toc-flat-filters" class="nav-link" data-scroll-target="#flat-filters"><span class="header-section-number">7.6</span> Flat filters</a></li>
  </ul></li>
  <li><a href="#aggregation-methodology" id="toc-aggregation-methodology" class="nav-link" data-scroll-target="#aggregation-methodology"><span class="header-section-number">8</span> Aggregation methodology</a>
  <ul>
  <li><a href="#aggregation-dimensions" id="toc-aggregation-dimensions" class="nav-link" data-scroll-target="#aggregation-dimensions"><span class="header-section-number">8.1</span> Aggregation dimensions</a></li>
  <li><a href="#aggregation-modes" id="toc-aggregation-modes" class="nav-link" data-scroll-target="#aggregation-modes"><span class="header-section-number">8.2</span> Aggregation modes</a>
  <ul class="collapse">
  <li><a href="#mode-1-keep-filtered-codes-separate" id="toc-mode-1-keep-filtered-codes-separate" class="nav-link" data-scroll-target="#mode-1-keep-filtered-codes-separate"><span class="header-section-number">8.2.1</span> Mode 1: Keep filtered codes separate</a></li>
  <li><a href="#mode-2-combine-all-filtered-values-into-one-output" id="toc-mode-2-combine-all-filtered-values-into-one-output" class="nav-link" data-scroll-target="#mode-2-combine-all-filtered-values-into-one-output"><span class="header-section-number">8.2.2</span> Mode 2: Combine all filtered values into one output</a></li>
  <li><a href="#mode-3-aggregate-selected-filter-groups-separately" id="toc-mode-3-aggregate-selected-filter-groups-separately" class="nav-link" data-scroll-target="#mode-3-aggregate-selected-filter-groups-separately"><span class="header-section-number">8.2.3</span> Mode 3: Aggregate selected filter groups separately</a>
  <ul class="collapse">
  <li><a href="#leaf-selection" id="toc-leaf-selection" class="nav-link" data-scroll-target="#leaf-selection"><span class="header-section-number">8.2.3.1</span> Leaf selection</a></li>
  </ul></li>
  <li><a href="#mode-4-aggregate-by-direct-children" id="toc-mode-4-aggregate-by-direct-children" class="nav-link" data-scroll-target="#mode-4-aggregate-by-direct-children"><span class="header-section-number">8.2.4</span> Mode 4: Aggregate by direct children</a>
  <ul class="collapse">
  <li><a href="#filtering-through-one-classification-and-aggregating-through-another" id="toc-filtering-through-one-classification-and-aggregating-through-another" class="nav-link" data-scroll-target="#filtering-through-one-classification-and-aggregating-through-another"><span class="header-section-number">8.2.4.1</span> Filtering through one classification and aggregating through another</a></li>
  <li><a href="#direct-child-parent-selection-rule" id="toc-direct-child-parent-selection-rule" class="nav-link" data-scroll-target="#direct-child-parent-selection-rule"><span class="header-section-number">8.2.4.2</span> Direct-child parent-selection rule</a></li>
  <li><a href="#several-aggregation-parents" id="toc-several-aggregation-parents" class="nav-link" data-scroll-target="#several-aggregation-parents"><span class="header-section-number">8.2.4.3</span> Several aggregation parents</a></li>
  <li><a href="#parent-whose-children-are-leaves" id="toc-parent-whose-children-are-leaves" class="nav-link" data-scroll-target="#parent-whose-children-are-leaves"><span class="header-section-number">8.2.4.4</span> Parent whose children are leaves</a></li>
  <li><a href="#selecting-a-leaf-as-the-aggregation-parent" id="toc-selecting-a-leaf-as-the-aggregation-parent" class="nav-link" data-scroll-target="#selecting-a-leaf-as-the-aggregation-parent"><span class="header-section-number">8.2.4.5</span> Selecting a leaf as the aggregation parent</a></li>
  <li><a href="#overlapping-direct-child-outputs" id="toc-overlapping-direct-child-outputs" class="nav-link" data-scroll-target="#overlapping-direct-child-outputs"><span class="header-section-number">8.2.4.6</span> Overlapping direct-child outputs</a></li>
  </ul></li>
  <li><a href="#mode-5-custom-aggregation" id="toc-mode-5-custom-aggregation" class="nav-link" data-scroll-target="#mode-5-custom-aggregation"><span class="header-section-number">8.2.5</span> Mode 5: Custom aggregation</a>
  <ul class="collapse">
  <li><a href="#output-naming" id="toc-output-naming" class="nav-link" data-scroll-target="#output-naming"><span class="header-section-number">8.2.5.1</span> Output naming</a></li>
  <li><a href="#parent-and-descendant-selected-together" id="toc-parent-and-descendant-selected-together" class="nav-link" data-scroll-target="#parent-and-descendant-selected-together"><span class="header-section-number">8.2.5.2</span> Parent and descendant selected together</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  <li><a href="#filtering-and-aggregation-are-independent" id="toc-filtering-and-aggregation-are-independent" class="nav-link" data-scroll-target="#filtering-and-aggregation-are-independent"><span class="header-section-number">9</span> Filtering and aggregation are independent</a>
  <ul>
  <li><a href="#cross-classification-example" id="toc-cross-classification-example" class="nav-link" data-scroll-target="#cross-classification-example"><span class="header-section-number">9.1</span> Cross-classification example</a></li>
  </ul></li>
  <li><a href="#numerical-aggregation" id="toc-numerical-aggregation" class="nav-link" data-scroll-target="#numerical-aggregation"><span class="header-section-number">10</span> Numerical aggregation</a>
  <ul>
  <li><a href="#value-calculation" id="toc-value-calculation" class="nav-link" data-scroll-target="#value-calculation"><span class="header-section-number">10.1</span> Value calculation</a></li>
  </ul></li>
  <li><a href="#flag-aggregation" id="toc-flag-aggregation" class="nav-link" data-scroll-target="#flag-aggregation"><span class="header-section-number">11</span> Flag aggregation</a></li>
  <li><a href="#year-aggregation" id="toc-year-aggregation" class="nav-link" data-scroll-target="#year-aggregation"><span class="header-section-number">12</span> Year aggregation</a></li>
  <li><a href="#measured-element-processing" id="toc-measured-element-processing" class="nav-link" data-scroll-target="#measured-element-processing"><span class="header-section-number">13</span> Measured-element processing</a></li>
  <li><a href="#aggregation-output-tables" id="toc-aggregation-output-tables" class="nav-link" data-scroll-target="#aggregation-output-tables"><span class="header-section-number">14</span> Aggregation output tables</a></li>
  <li><a href="#graphs" id="toc-graphs" class="nav-link" data-scroll-target="#graphs"><span class="header-section-number">15</span> Graphs</a>
  <ul>
  <li><a href="#aggregated-total" id="toc-aggregated-total" class="nav-link" data-scroll-target="#aggregated-total"><span class="header-section-number">15.1</span> Aggregated total</a></li>
  <li><a href="#categorize-by" id="toc-categorize-by" class="nav-link" data-scroll-target="#categorize-by"><span class="header-section-number">15.2</span> Categorize by</a>
  <ul class="collapse">
  <li><a href="#aggregation-composition" id="toc-aggregation-composition" class="nav-link" data-scroll-target="#aggregation-composition"><span class="header-section-number">15.2.1</span> Aggregation composition</a></li>
  <li><a href="#final-result-column" id="toc-final-result-column" class="nav-link" data-scroll-target="#final-result-column"><span class="header-section-number">15.2.2</span> Final result column</a></li>
  </ul></li>
  <li><a href="#stacked-bar-chart" id="toc-stacked-bar-chart" class="nav-link" data-scroll-target="#stacked-bar-chart"><span class="header-section-number">15.3</span> Stacked bar chart</a></li>
  <li><a href="#relative-stacked-bar-chart" id="toc-relative-stacked-bar-chart" class="nav-link" data-scroll-target="#relative-stacked-bar-chart"><span class="header-section-number">15.4</span> Relative stacked bar chart</a></li>
  <li><a href="#component-time-series" id="toc-component-time-series" class="nav-link" data-scroll-target="#component-time-series"><span class="header-section-number">15.5</span> Component time series</a></li>
  <li><a href="#treemap" id="toc-treemap" class="nav-link" data-scroll-target="#treemap"><span class="header-section-number">15.6</span> Treemap</a></li>
  </ul></li>
  <li><a href="#dataset-comparison" id="toc-dataset-comparison" class="nav-link" data-scroll-target="#dataset-comparison"><span class="header-section-number">16</span> Dataset comparison</a>
  <ul>
  <li><a href="#eligibility-and-required-sequence" id="toc-eligibility-and-required-sequence" class="nav-link" data-scroll-target="#eligibility-and-required-sequence"><span class="header-section-number">16.1</span> Eligibility and required sequence</a></li>
  <li><a href="#reuse-of-the-aggregation-state" id="toc-reuse-of-the-aggregation-state" class="nav-link" data-scroll-target="#reuse-of-the-aggregation-state"><span class="header-section-number">16.2</span> Reuse of the aggregation state</a></li>
  <li><a href="#matching-records-for-comparison" id="toc-matching-records-for-comparison" class="nav-link" data-scroll-target="#matching-records-for-comparison"><span class="header-section-number">16.3</span> Matching records for comparison</a></li>
  <li><a href="#comparison-values" id="toc-comparison-values" class="nav-link" data-scroll-target="#comparison-values"><span class="header-section-number">16.4</span> Comparison values</a></li>
  <li><a href="#comparison-statuses" id="toc-comparison-statuses" class="nav-link" data-scroll-target="#comparison-statuses"><span class="header-section-number">16.5</span> Comparison statuses</a></li>
  <li><a href="#differences-in-category-coverage" id="toc-differences-in-category-coverage" class="nav-link" data-scroll-target="#differences-in-category-coverage"><span class="header-section-number">16.6</span> Differences in category coverage</a></li>
  <li><a href="#comparison-outputs" id="toc-comparison-outputs" class="nav-link" data-scroll-target="#comparison-outputs"><span class="header-section-number">16.7</span> Comparison outputs</a></li>
  </ul></li>
  <li><a href="#outlier-analysis" id="toc-outlier-analysis" class="nav-link" data-scroll-target="#outlier-analysis"><span class="header-section-number">17</span> Outlier analysis</a>
  <ul>
  <li><a href="#measured-element-for-outlier-analysis" id="toc-measured-element-for-outlier-analysis" class="nav-link" data-scroll-target="#measured-element-for-outlier-analysis"><span class="header-section-number">17.1</span> Measured element for outlier analysis</a></li>
  <li><a href="#analyse-outliers-for" id="toc-analyse-outliers-for" class="nav-link" data-scroll-target="#analyse-outliers-for"><span class="header-section-number">17.2</span> Analyse outliers for</a></li>
  <li><a href="#outlier-metric" id="toc-outlier-metric" class="nav-link" data-scroll-target="#outlier-metric"><span class="header-section-number">17.3</span> Outlier metric</a>
  <ul class="collapse">
  <li><a href="#value" id="toc-value" class="nav-link" data-scroll-target="#value"><span class="header-section-number">17.3.1</span> Value</a></li>
  <li><a href="#year-on-year-absolute-change" id="toc-year-on-year-absolute-change" class="nav-link" data-scroll-target="#year-on-year-absolute-change"><span class="header-section-number">17.3.2</span> Year-on-year absolute change</a></li>
  <li><a href="#year-on-year-percentage-change" id="toc-year-on-year-percentage-change" class="nav-link" data-scroll-target="#year-on-year-percentage-change"><span class="header-section-number">17.3.3</span> Year-on-year percentage change</a></li>
  </ul></li>
  <li><a href="#distribution-by-year" id="toc-distribution-by-year" class="nav-link" data-scroll-target="#distribution-by-year"><span class="header-section-number">17.4</span> Distribution by year</a></li>
  <li><a href="#largest-strongest-records" id="toc-largest-strongest-records" class="nav-link" data-scroll-target="#largest-strongest-records"><span class="header-section-number">17.5</span> Largest / strongest records</a>
  <ul class="collapse">
  <li><a href="#value-1" id="toc-value-1" class="nav-link" data-scroll-target="#value-1"><span class="header-section-number">17.5.1</span> Value</a></li>
  <li><a href="#year-on-year-absolute-change-1" id="toc-year-on-year-absolute-change-1" class="nav-link" data-scroll-target="#year-on-year-absolute-change-1"><span class="header-section-number">17.5.2</span> Year-on-year absolute change</a></li>
  <li><a href="#year-on-year-percentage-change-1" id="toc-year-on-year-percentage-change-1" class="nav-link" data-scroll-target="#year-on-year-percentage-change-1"><span class="header-section-number">17.5.3</span> Year-on-year percentage change</a></li>
  </ul></li>
  <li><a href="#number-of-top-records-to-display" id="toc-number-of-top-records-to-display" class="nav-link" data-scroll-target="#number-of-top-records-to-display"><span class="header-section-number">17.6</span> Number of top records to display</a></li>
  <li><a href="#download-outlier-csv" id="toc-download-outlier-csv" class="nav-link" data-scroll-target="#download-outlier-csv"><span class="header-section-number">17.7</span> Download outlier CSV</a></li>
  </ul></li>
  <li><a href="#worked-user-scenarios" id="toc-worked-user-scenarios" class="nav-link" data-scroll-target="#worked-user-scenarios"><span class="header-section-number">18</span> Worked user scenarios</a>
  <ul>
  <li><a href="#scenario-1-filter-one-isscaap-group-keep-species-separate-and-aggregate-geographical-areas" id="toc-scenario-1-filter-one-isscaap-group-keep-species-separate-and-aggregate-geographical-areas" class="nav-link" data-scroll-target="#scenario-1-filter-one-isscaap-group-keep-species-separate-and-aggregate-geographical-areas"><span class="header-section-number">18.1</span> Scenario 1: Filter one ISSCAAP group, keep species separate and aggregate geographical areas</a></li>
  <li><a href="#scenario-2-aggregate-species-by-the-direct-isscaap-groups" id="toc-scenario-2-aggregate-species-by-the-direct-isscaap-groups" class="nav-link" data-scroll-target="#scenario-2-aggregate-species-by-the-direct-isscaap-groups"><span class="header-section-number">18.2</span> Scenario 2: Aggregate species by the direct ISSCAAP groups</a></li>
  <li><a href="#scenario-3-filter-species-using-isscaap-and-aggregate-them-using-taxonomic" id="toc-scenario-3-filter-species-using-isscaap-and-aggregate-them-using-taxonomic" class="nav-link" data-scroll-target="#scenario-3-filter-species-using-isscaap-and-aggregate-them-using-taxonomic"><span class="header-section-number">18.3</span> Scenario 3: Filter species using ISSCAAP and aggregate them using TAXONOMIC</a></li>
  <li><a href="#scenario-4-apply-different-aggregation-rules-to-several-dimensions" id="toc-scenario-4-apply-different-aggregation-rules-to-several-dimensions" class="nav-link" data-scroll-target="#scenario-4-apply-different-aggregation-rules-to-several-dimensions"><span class="header-section-number">18.4</span> Scenario 4: Apply different aggregation rules to several dimensions</a></li>
  </ul></li>
  <li><a href="#validation-and-error-handling" id="toc-validation-and-error-handling" class="nav-link" data-scroll-target="#validation-and-error-handling"><span class="header-section-number">19</span> Validation and error handling</a>
  <ul>
  <li><a href="#dataset-and-aggregation-checks" id="toc-dataset-and-aggregation-checks" class="nav-link" data-scroll-target="#dataset-and-aggregation-checks"><span class="header-section-number">19.1</span> Dataset and aggregation checks</a></li>
  <li><a href="#hierarchy-and-aggregation-checks" id="toc-hierarchy-and-aggregation-checks" class="nav-link" data-scroll-target="#hierarchy-and-aggregation-checks"><span class="header-section-number">19.2</span> Hierarchy and aggregation checks</a></li>
  <li><a href="#aggregation-error-diagnostics" id="toc-aggregation-error-diagnostics" class="nav-link" data-scroll-target="#aggregation-error-diagnostics"><span class="header-section-number">19.3</span> Aggregation error diagnostics</a></li>
  <li><a href="#per-measured-element-warnings" id="toc-per-measured-element-warnings" class="nav-link" data-scroll-target="#per-measured-element-warnings"><span class="header-section-number">19.4</span> Per-measured-element warnings</a></li>
  </ul></li>
  <li><a href="#current-implementation-constraints" id="toc-current-implementation-constraints" class="nav-link" data-scroll-target="#current-implementation-constraints"><span class="header-section-number">20</span> Current implementation constraints</a></li>
  <li><a href="#main-functions-in-the-application" id="toc-main-functions-in-the-application" class="nav-link" data-scroll-target="#main-functions-in-the-application"><span class="header-section-number">21</span> Main functions in the application</a></li>
  <li><a href="#maintenance-guidance-trigger-link-and-repository" id="toc-maintenance-guidance-trigger-link-and-repository" class="nav-link" data-scroll-target="#maintenance-guidance-trigger-link-and-repository"><span class="header-section-number">22</span> Maintenance guidance, trigger link and repository</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">23</span> Conclusion</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fisheries Aggregation Shiny App</h1>
<p class="subtitle lead">Functional and Methodological Documentation</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lyubov Doroshenko </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="document-purpose" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Document purpose</h1>
<p>This document provides functional, methodological and technical documentation for the <strong>Fisheries Aggregation Shiny App</strong>.</p>
<p>The application supports the exploration, filtering, hierarchical aggregation, visualization, comparison and outlier analysis of Fisheries datasets available through the FAO Statistical Working System, referred to throughout this document as <strong>SWS</strong>.</p>
<p>The document has four main objectives:</p>
<ol type="1">
<li>Explain the application workflow from dataset loading to output download.</li>
<li>Describe precisely how filters and aggregation modes affect the data.</li>
<li>Document the methodological rules used to aggregate values and flags.</li>
<li>Provide worked examples that can be used for testing and user training.</li>
<li>Document the technical implementation of the application, including the structure of the R script, the location and organisation of the source-code repository, the trigger link used to launch the application, and the main information required for future maintenance and updates.</li>
</ol>
</section>
<section id="application-overview" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Application overview</h1>
<section id="main-objective" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="main-objective"><span class="header-section-number">2.1</span> Main objective</h2>
<p>The application provides one common interface for processing multiple Fisheries datasets that share a broadly consistent data structure.</p>
<p>Users can:</p>
<ul>
<li>Select a <strong>current</strong> or <strong>disseminated dataset</strong>;</li>
<li>Inspect the dataset structure and available measured elements;</li>
<li>Restrict the data by <strong>year</strong> and <strong>measured element</strong>;</li>
<li>Aggregate one or more hierarchical dimensions;</li>
<li>Keep some dimensions at their original level;</li>
<li>Preserve or aggregate observation flags;</li>
<li>Aggregate multiple years into a single period;</li>
<li>Review results separately by measured element;</li>
<li>Visualize totals and compositions;</li>
<li>Compare a current dataset with a disseminated or tagged dataset;</li>
<li>Screen aggregated results for possible outliers;</li>
<li>Download aggregated, comparison and outlier tables.</li>
</ul>
</section>
<section id="conceptual-workflow" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="conceptual-workflow"><span class="header-section-number">2.2</span> Conceptual workflow</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
A[Initialize SWS client] --&gt; B[Select dataset group]
B --&gt; C[Load dataset]
C --&gt; D[Inspect dataset summary]
D --&gt; E[Select years]
E --&gt; F[Choose measured elements]
F --&gt; G[Apply dimension filters]
G --&gt; H[Choose aggregation mode by dimension]
H --&gt; I[Run aggregation]
I --&gt; J[Review output tables]
I --&gt; K[Review output graphs]
I --&gt; L[Run comparison]
I --&gt; M[Run outlier analysis]
J --&gt; N[Download CSV]
L --&gt; N
M --&gt; N
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="separation-between-filtering-and-aggregation" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="separation-between-filtering-and-aggregation"><span class="header-section-number">2.3</span> Separation between filtering and aggregation</h2>
<p>The application treats filtering and aggregation as two different operations.</p>
<p><strong>Filtering determines which records remain in the working dataset.</strong></p>
<p><strong>Aggregation determines how those remaining records are grouped in the output.</strong></p>
<p>For example:</p>
<ul>
<li>filtering species through the ISSCAAP hierarchy determines which raw species records are retained;</li>
<li>aggregating those filtered records through the TAXONOMIC hierarchy determines how the retained species are grouped in the result.</li>
</ul>
<p>The filtering hierarchy and aggregation hierarchy therefore do not need to be the same.</p>
</section>
</section>
<section id="application-architecture" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Application architecture</h1>
<p>The user interface contains seven principal pages.</p>
<div class="cell">
<div id="tbl-app-pages" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-app-pages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Application navigation pages
</figcaption>
<div aria-describedby="tbl-app-pages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 22%">
<col style="width: 71%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Page</th>
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Data selection</td>
<td style="text-align: left;">Initialize the client and load a dataset</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Dataset summary</td>
<td style="text-align: left;">Inspect metadata, measured elements, raw time series and source rows</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Filters &amp; aggregation</td>
<td style="text-align: left;">Select years, apply filters and configure aggregation</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Dataset table</td>
<td style="text-align: left;">Review and download aggregation outputs</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Graphs</td>
<td style="text-align: left;">Visualize totals and compositions</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Comparison</td>
<td style="text-align: left;">Compare current output with disseminated or tagged data</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Outlier analysis</td>
<td style="text-align: left;">Screen aggregated outputs for unusual levels or changes</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="1">
<li><p><strong>Data Selection</strong> page allows the user to connect to SWS by clicking the <strong>Initialise Client</strong> button, with no additional action required. The user can then select the <strong>Dataset group</strong>, with <strong>Current Fisheries dataset</strong> selected by default, and choose a dataset of interest from the supported Fisheries datasets.</p></li>
<li><p><strong>Dataset Summary</strong> page provides an overview of the main characteristics of the loaded dataset, including the number of records and the available measured elements. It also includes graphical and tabular previews of the raw dataset over time.</p></li>
<li><p><strong>Filters &amp; Aggregation</strong> page allows the user to select the time period and measured element(s) of interest, apply filters to the available dataset dimensions, and define the desired aggregation settings.</p></li>
<li><p><strong>Dataset Table</strong> page displays the aggregation results and allows them to be downloaded. If more than one measured element is selected, a separate output is provided for each measured element.</p></li>
<li><p><strong>Graphs</strong> page allows the user to visualise the aggregation results using the available dataset dimensions and different graphical representations.</p></li>
<li><p><strong>Comparison</strong> page allows the user to select a comparison data source and the corresponding disseminated or tagged dataset. It provides downloadable comparison outputs containing either all comparison rows or only those for which differences are detected.</p></li>
<li><p><strong>Outlier Analysis</strong> page provides graphical tools for identifying and exploring potential outliers, including the distribution of values by year and the largest records according to each available dimension. In this application, outlier analysis is used as a screening tool to inspect unusually large values and year-on-year changes in the aggregated output. It does not apply a formal statistical outlier-detection rule.</p></li>
</ol>
</section>
<section id="supported-datasets" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Supported datasets</h1>
<section id="dataset-registry" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="dataset-registry"><span class="header-section-number">4.1</span> Dataset registry</h2>
<p>The application supports the following datasets:</p>
<div class="cell">
<div id="tbl-supported-datasets" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-supported-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Datasets currently registered in the application
</figcaption>
<div aria-describedby="tbl-supported-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset_ID</th>
<th style="text-align: left;">Label</th>
<th style="text-align: left;">Group</th>
<th style="text-align: left;">Data_type</th>
<th style="text-align: left;">Production_source</th>
<th style="text-align: left;">Currency_flag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">capture</td>
<td style="text-align: left;">Capture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">fi_capture_cecaf</td>
<td style="text-align: left;">CECAF regional capture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fi_capture_gfcm</td>
<td style="text-align: left;">GFCM regional capture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">fi_capture_recofi</td>
<td style="text-align: left;">RECOFI regional capture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fi_capture_seatl</td>
<td style="text-align: left;">SEATL regional capture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">aqua</td>
<td style="text-align: left;">Aquaculture production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fi_global_production</td>
<td style="text-align: left;">Global production</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">capture_price</td>
<td style="text-align: left;">Capture price</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Price</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">aquaculture_value</td>
<td style="text-align: left;">Aquaculture value</td>
<td style="text-align: left;">Current</td>
<td style="text-align: left;">Value</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">aqua_disseminated</td>
<td style="text-align: left;">Aquaculture production validated</td>
<td style="text-align: left;">Disseminated</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capture_disseminated</td>
<td style="text-align: left;">Capture production disseminated</td>
<td style="text-align: left;">Disseminated</td>
<td style="text-align: left;">Quantity</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="dataset-groups" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="dataset-groups"><span class="header-section-number">4.2</span> Dataset groups</h2>
<p>The data-selection page separates datasets into:</p>
<ul>
<li><strong>Current Fisheries datasets</strong></li>
<li><strong>Previous disseminated datasets</strong></li>
</ul>
<p>A current dataset may be used as the main dataset in the Comparison page.</p>
<p>A disseminated dataset may be filtered, aggregated, graphed and analysed for outliers, but it cannot currently be used as the main dataset in a comparison.</p>
</section>
</section>
<section id="dataset-structure" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Dataset structure</h1>
<section id="common-columns" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="common-columns"><span class="header-section-number">5.1</span> Common columns</h2>
<p>The application expects the following common Fisheries columns.</p>
<div class="cell">
<div id="tbl-common-columns" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-common-columns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Common Fisheries dataset columns
</figcaption>
<div aria-describedby="tbl-common-columns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 35%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Meaning</th>
<th style="text-align: left;">Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">timePointYears</td>
<td style="text-align: left;">Reference year</td>
<td style="text-align: left;">Filter and optional temporal aggregation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Value</td>
<td style="text-align: left;">Numeric observation value</td>
<td style="text-align: left;">Value to aggregate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">geographicAreaM49_fi</td>
<td style="text-align: left;">Country or geographical-area code</td>
<td style="text-align: left;">Filter and aggregation dimension</td>
</tr>
<tr class="even">
<td style="text-align: left;">fisheriesAsfis</td>
<td style="text-align: left;">Species or ASFIS code</td>
<td style="text-align: left;">Filter and aggregation dimension</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fisheriesCatchArea</td>
<td style="text-align: left;">Fishing-area code</td>
<td style="text-align: left;">Filter and aggregation dimension</td>
</tr>
<tr class="even">
<td style="text-align: left;">measuredElement</td>
<td style="text-align: left;">Measured-element code</td>
<td style="text-align: left;">Filter and output separation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flagObservationStatus</td>
<td style="text-align: left;">Observation-status flag</td>
<td style="text-align: left;">Filter and optional aggregation grouping</td>
</tr>
<tr class="even">
<td style="text-align: left;">flagMethod</td>
<td style="text-align: left;">Method flag</td>
<td style="text-align: left;">Flag aggregation</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="optional-columns" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="optional-columns"><span class="header-section-number">5.2</span> Optional columns</h2>
<p>Some datasets additionally contain:</p>
<ul>
<li><code>fisheriesProductionSource</code></li>
<li><code>flagCurrency</code></li>
</ul>
<p>The production-source dimension is available only when its dataset column exists.</p>
<p>The currency flag is used as a filter where available. It is also retained as an analytical key so values expressed in different currencies are not unintentionally merged.</p>
</section>
</section>
<section id="data-loading-and-preprocessing" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Data loading and preprocessing</h1>
<section id="client-initialization-and-dataset-loading" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="client-initialization-and-dataset-loading"><span class="header-section-number">6.1</span> Client initialization and dataset loading</h2>
<p>The user must initialize the SWS client before selecting and loading a dataset.</p>
<div id="fig-initialisation-and-datasets" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-initialisation-and-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/datasets_initialise.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-initialisation-and-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Client initialisation
</figcaption>
</figure>
</div>
<p>After loading a dataset, the application validates the expected common columns.</p>
<p>Loading stops when one or more required columns are absent.</p>
<p>This prevents later filtering or aggregation operations from silently using an incomplete structure.</p>
</section>
<section id="dataset-summary" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="dataset-summary"><span class="header-section-number">6.2</span> Dataset summary</h2>
<p>After a dataset is loaded, the application displays a summary of its main characteristics.</p>
<p>The summary includes:</p>
<ul>
<li>the selected dataset and dataset group;</li>
<li>the number of records under the configured measured-element roots;</li>
<li>the available year range;</li>
<li>the number of configured measured-element roots;</li>
<li>the configured measured-element roots;</li>
<li>the number of configured roots with usable data;</li>
<li>the configured roots with usable data;</li>
<li>the main dimensions available in the dataset.</li>
</ul>
<p>The summary is restricted to the measured-element roots configured for the loaded dataset in SWS.</p>
<div id="fig-dataset-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/data_summary_loaded_dataset.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Dataset summary
</figcaption>
</figure>
</div>
</section>
</section>
<section id="filtering-methodology" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Filtering methodology</h1>
<section id="general-rule" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="general-rule"><span class="header-section-number">7.1</span> General rule</h2>
<p>Filters are applied to the loaded dataset before aggregation.</p>
<p>A filter does not directly determine the output grouping. It determines only which source rows remain available to the aggregation procedure.</p>
<p>Filters are applied sequentially:</p>
<ol type="1">
<li>year filter;</li>
<li>measured-element selection;</li>
<li>geographical-area filter;</li>
<li>species filter;</li>
<li>fishing-area filter;</li>
<li>production-source filter, where available;</li>
<li>observation-status filter;</li>
<li>currency filter, where available.</li>
</ol>
<p>The exact active dimensions depend on the columns present in the loaded dataset.</p>
<p>When no value is selected for a dimension, that dimension does not restrict the dataset.</p>
<p>For example, leaving the geographical-area tree empty keeps all geographical-area codes that remain valid under the dataset configuration.</p>
<div id="fig-filters-aggregation-page" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-filters-aggregation-page-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/filters_aggregation_page.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-filters-aggregation-page-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Filters &amp; Aggregation page
</figcaption>
</figure>
</div>
</section>
<section id="year-filter" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="year-filter"><span class="header-section-number">7.2</span> Year filter</h2>
<p>The year slider defines an inclusive range.</p>
<p>For a range from 2015 to 2020, rows are retained when:</p>
<p><span class="math display">\[
    2015 \leq \text{year} \leq 2020.
\]</span></p>
<p>The page also provides shortcuts for:</p>
<ul>
<li>full range;</li>
<li>latest 10 years;</li>
<li>latest 20 years.</li>
</ul>
</section>
<section id="measured-element-filter" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="measured-element-filter"><span class="header-section-number">7.3</span> Measured-element filter</h2>
<p>The measured-element selector shows only measured-element roots that satisfy both conditions:</p>
<ol type="1">
<li>the root is configured for the dataset in SWS metadata;</li>
<li>the loaded dataset contains at least one usable row for that root.</li>
</ol>
<p>The selected measured elements are processed independently during aggregation.</p>
<p>For example, selecting <code>FI_001</code> and <code>FI_002</code> produces two separate output tabs rather than summing the two measured elements together.</p>
</section>
<section id="hierarchical-filters" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="hierarchical-filters"><span class="header-section-number">7.4</span> Hierarchical filters</h2>
<p>The following dimensions use hierarchy trees:</p>
<ul>
<li>geographical area;</li>
<li>species or ASFIS;</li>
<li>fishing area;</li>
<li>production source, where available.</li>
</ul>
<div id="fig-geographical-filter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-geographical-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/geographical_area_filter.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-geographical-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Geographical area filter
</figcaption>
</figure>
</div>
<div id="fig-asfis-filter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asfis-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/asfis_filter.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asfis-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Asfis filter
</figcaption>
</figure>
</div>
<div id="fig-fishing-area-filter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fishing-area-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/fishing_area_filter.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fishing-area-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Fishing area filter
</figcaption>
</figure>
</div>
<p>Selecting a hierarchy node includes:</p>
<ul>
<li>the selected node itself;</li>
<li>all descendant codes under that node.</li>
</ul>
<section id="example" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="example"><span class="header-section-number">7.4.1</span> Example</h3>
<p>Assume the hierarchy is:</p>
<pre class="text"><code>ISSCAAP
├── 1501
│   ├── Species A
│   └── Species B
├── 1502
│   └── Species C
└── 1503
├── Species D
└── Species E</code></pre>
<p>Selecting <code>1501</code> in the filter retains:</p>
<ul>
<li>the code <code>1501</code>, when it occurs as a data value;</li>
<li>Species A;</li>
<li>Species B.</li>
</ul>
<p>It does not retain Species C, D or E unless they are included through another selected filter branch.</p>
</section>
</section>
<section id="most-specific-filter-selection-rule" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="most-specific-filter-selection-rule"><span class="header-section-number">7.5</span> Most-specific filter-selection rule</h2>
<p>Hierarchical filters use the <strong>most-specific selected nodes</strong> as effective filter roots.</p>
<p>When a parent and one or more of its descendants are explicitly selected, the parent is removed from the effective selection and the more specific selections are retained.</p>
<section id="example-1" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="example-1"><span class="header-section-number">7.5.1</span> Example</h3>
<div class="cell">
<div id="tbl-most-specific-filter" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-most-specific-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Most-specific hierarchical filtering
</figcaption>
<div aria-describedby="tbl-most-specific-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Visible_selection</th>
<th style="text-align: left;">Effective_filter_roots</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ISSCAAP only</td>
<td style="text-align: left;">ISSCAAP</td>
<td style="text-align: left;">All descendants of ISSCAAP remain</td>
</tr>
<tr class="even">
<td style="text-align: left;">1501 only</td>
<td style="text-align: left;">1501</td>
<td style="text-align: left;">Only the 1501 branch remains</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ISSCAAP + 1501 + 1502</td>
<td style="text-align: left;">1501 and 1502</td>
<td style="text-align: left;">Only the explicitly selected 1501 and 1502 branches remain</td>
</tr>
<tr class="even">
<td style="text-align: left;">1501 + 1502</td>
<td style="text-align: left;">1501 and 1502</td>
<td style="text-align: left;">Only the 1501 and 1502 branches remain</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This rule ensures that, when both a parent and one or more of its descendants are selected, the more specific descendant selections determine the effective filter.</p>
</section>
</section>
<section id="flat-filters" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="flat-filters"><span class="header-section-number">7.6</span> Flat filters</h2>
<p>Observation flags and currency flags are treated as flat dimensions.</p>
<div id="fig-observation-flag-filter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-observation-flag-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/observation_flag_filter.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-observation-flag-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Observation flag filter
</figcaption>
</figure>
</div>
<p>They do not have descendant expansion.</p>
<p>For example, selecting observation flags <code>A</code> and <code>E</code> retains rows whose observation-status flag is exactly <code>A</code> or <code>E</code>.</p>
<p>The <strong>Reset page</strong> button clears the current filters, aggregation settings and generated results, restoring the page to its initial state.</p>
</section>
</section>
<section id="aggregation-methodology" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Aggregation methodology</h1>
<section id="aggregation-dimensions" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="aggregation-dimensions"><span class="header-section-number">8.1</span> Aggregation dimensions</h2>
<p>The following dimensions can be aggregated independently.</p>
<div class="cell">
<div id="tbl-aggregation-dimensions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-aggregation-dimensions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Hierarchical aggregation dimensions
</figcaption>
<div aria-describedby="tbl-aggregation-dimensions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 38%">
<col style="width: 26%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimension</th>
<th style="text-align: left;">Dataset_column</th>
<th style="text-align: left;">Other_output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Country / geographical area</td>
<td style="text-align: left;">geographicAreaM49_fi</td>
<td style="text-align: left;">Other filtered geographical areas</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species / ASFIS</td>
<td style="text-align: left;">fisheriesAsfis</td>
<td style="text-align: left;">Other filtered species</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fishing area</td>
<td style="text-align: left;">fisheriesCatchArea</td>
<td style="text-align: left;">Other filtered fishing areas</td>
</tr>
<tr class="even">
<td style="text-align: left;">Production source / environment type</td>
<td style="text-align: left;">fisheriesProductionSource</td>
<td style="text-align: left;">Other filtered production sources</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="aggregation-modes" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="aggregation-modes"><span class="header-section-number">8.2</span> Aggregation modes</h2>
<p>Each available aggregation dimension has its own independently selected mode.</p>
<div class="cell">
<div id="tbl-aggregation-modes" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-aggregation-modes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Aggregation modes available for each hierarchical dimension
</figcaption>
<div aria-describedby="tbl-aggregation-modes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mode</th>
<th style="text-align: left;">Main_effect</th>
<th style="text-align: left;">Treatment_of_remaining_filtered_codes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keep filtered codes separate</td>
<td style="text-align: left;">The dimension remains at its filtered raw-code level</td>
<td style="text-align: left;">They remain separate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Combine all filtered values into one output</td>
<td style="text-align: left;">Every filtered code in the dimension is mapped to one output</td>
<td style="text-align: left;">They are included in the one combined output</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aggregate selected filter groups separately</td>
<td style="text-align: left;">Each effective hierarchy group selected in the filter becomes an output</td>
<td style="text-align: left;">They are assigned to the dimension-specific Other output when not mapped</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aggregate by direct children</td>
<td style="text-align: left;">Every direct child of each selected aggregation parent becomes an output</td>
<td style="text-align: left;">They are assigned to the dimension-specific Other output</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Custom aggregation</td>
<td style="text-align: left;">Selected nodes and descendants are combined into one custom output</td>
<td style="text-align: left;">They are assigned to the dimension-specific Other output</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="mode-1-keep-filtered-codes-separate" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="mode-1-keep-filtered-codes-separate"><span class="header-section-number">8.2.1</span> Mode 1: Keep filtered codes separate</h3>
<p>No aggregation map is applied to that dimension.</p>
<p>Every detailed code remaining after filtering stays as a separate value in the result.</p>
<p><strong>Example</strong></p>
<p>After filtering, the remaining species are:</p>
<pre class="text"><code>Species A
Species B
Species C</code></pre>
<p>With species set to <strong>Keep filtered codes separate</strong>, all three species codes remain distinct.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Current execution requirement
</div>
</div>
<div class="callout-body-container callout-body">
<p>This option operates at the dimension level. In the current implementation, the Run button still requires at least one aggregation action overall.</p>
<p>When every dimension is set to “Keep filtered codes separate” and neither year aggregation nor observation-flag aggregation is selected, the application stops and asks the user to select at least one aggregation dimension.</p>
</div>
</div>
</section>
<section id="mode-2-combine-all-filtered-values-into-one-output" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="mode-2-combine-all-filtered-values-into-one-output"><span class="header-section-number">8.2.2</span> Mode 2: Combine all filtered values into one output</h3>
<p>All remaining codes for that dimension are combined into one output.</p>
<p>The output code follows this rule:</p>
<ul>
<li>when exactly one effective hierarchy node was selected in the corresponding filter, that selected code is retained;</li>
<li>when no effective filter node or several effective filter nodes were selected, the output code is <code>TOTAL</code>.</li>
</ul>
<p><strong>Example A: one selected filter group</strong></p>
<pre class="text"><code>Filter: World, code 1
Aggregation mode: Combine all filtered values into one output
Output geographical-area code: 1</code></pre>
<p><strong>Example B: several selected filter groups</strong></p>
<pre class="text"><code>Filter: Europe and Asia
Aggregation mode: Combine all filtered values into one output
Output geographical-area code: TOTAL</code></pre>
<p><strong>Illustrative numerical example</strong></p>
<p>Assume that, after filtering, three species groups remain in the dataset:</p>
<div class="cell">
<div id="tbl-total-aggregation-input" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-total-aggregation-input-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Values remaining after filtering
</figcaption>
<div aria-describedby="tbl-total-aggregation-input-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Species_group</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1501</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">1502</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1503</td>
<td style="text-align: right;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>If <strong>Combine all filtered values into one output</strong> is selected for the species dimension, all three filtered values are assigned to the same output group.</p>
<p>The aggregated value is therefore:</p>
<p><span class="math display">\[
30 + 40 + 50 = 120
\]</span></p>
<div class="cell">
<div id="tbl-total-aggregation-result" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-total-aggregation-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Result after total aggregation
</figcaption>
<div aria-describedby="tbl-total-aggregation-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Output_group</th>
<th style="text-align: right;">Aggregated_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TOTAL</td>
<td style="text-align: right;">120</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The three species groups are therefore replaced by a single <code>TOTAL</code> output with an aggregated value of <code>120</code>.</p>
</section>
<section id="mode-3-aggregate-selected-filter-groups-separately" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="mode-3-aggregate-selected-filter-groups-separately"><span class="header-section-number">8.2.3</span> Mode 3: Aggregate selected filter groups separately</h3>
<p>This mode uses the effective groups selected in the <strong>filter tree</strong>.</p>
<p>Each effective filter group becomes a separate output and includes all filtered descendants beneath it.</p>
<p><strong>Example A: regional groups</strong></p>
<pre class="text"><code>Filter groups: Europe and Asia
Aggregation mode: Aggregate selected filter groups separately

Outputs:
- Europe
- Asia</code></pre>
<p><strong>Example B: ISSCAAP classes</strong></p>
<pre class="text"><code>Filter groups: 1501, 1502 and 1503
Aggregation mode: Aggregate selected filter groups separately

Outputs:
- 1501
- 1502
- 1503</code></pre>
<p><strong>Example C: ISSCAAP root only</strong></p>
<pre class="text"><code>Filter group: ISSCAAP
Aggregation mode: Aggregate selected filter groups separately

Output:
  - ISSCAAP</code></pre>
<p>This mode does <strong>not</strong> automatically split ISSCAAP into its direct children. Splitting by direct children is a separate aggregation mode.</p>
<section id="leaf-selection" class="level4" data-number="8.2.3.1">
<h4 data-number="8.2.3.1" class="anchored" data-anchor-id="leaf-selection"><span class="header-section-number">8.2.3.1</span> Leaf selection</h4>
<p>A leaf selected as a filter group works normally in this mode.</p>
<pre class="text"><code>Filter group: one species leaf
Aggregation mode: Aggregate selected filter groups separately
Output: that species leaf</code></pre>
<p>The mode groups by the selected filter groups themselves; therefore a selected group does not need to have children.</p>
</section>
</section>
<section id="mode-4-aggregate-by-direct-children" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="mode-4-aggregate-by-direct-children"><span class="header-section-number">8.2.4</span> Mode 4: Aggregate by direct children</h3>
<p>This mode uses selections made in the independent <strong>aggregation-classification tree</strong>.</p>
<p>For every selected parent:</p>
<ol type="1">
<li>identify its immediate children;</li>
<li>create one output for each immediate child;</li>
<li>assign the direct child and all descendants beneath that child to the corresponding output;</li>
<li>combine filtered codes outside the selected classifications into the dimension-specific <code>Other</code> output.</li>
</ol>
<p><strong>ISSCAAP example</strong></p>
<p>Assume:</p>
<pre class="text"><code>ISSCAAP
├── 1501 - Freshwater fishes
├── 1502 - Diadromous fishes
└── 1503 - Marine fishes</code></pre>
<p>Selecting <code>ISSCAAP</code> as the aggregation parent produces:</p>
<pre class="text"><code>1501 - Freshwater fishes
1502 - Diadromous fishes
1503 - Marine fishes</code></pre>
<p>while selecting <code>TAXONOMIC</code> as the aggregation parent produces:</p>
<pre class="text"><code>8501 - Fishes
8502 - Crustaceans
8503 - Molluscs</code></pre>
<p>It does not produce one output called <code>ISSCAAP</code> or <code>TAXONOMIC</code>.</p>
<p><strong>Numerical example</strong></p>
<div class="cell">
<div id="tbl-direct-child-input" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-direct-child-input-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Illustrative raw species records
</figcaption>
<div aria-describedby="tbl-direct-child-input-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">raw_species</th>
<th style="text-align: left;">direct_ISSCAAP_child</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Species A</td>
<td style="text-align: left;">1501</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species B</td>
<td style="text-align: left;">1501</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species C</td>
<td style="text-align: left;">1502</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species D</td>
<td style="text-align: left;">1503</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species E</td>
<td style="text-align: left;">1503</td>
<td style="text-align: right;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-direct-child-output" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-direct-child-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Illustrative direct-child aggregation output
</figcaption>
<div aria-describedby="tbl-direct-child-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">direct_ISSCAAP_child</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1501</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">1502</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1503</td>
<td style="text-align: right;">90</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="filtering-through-one-classification-and-aggregating-through-another" class="level4" data-number="8.2.4.1">
<h4 data-number="8.2.4.1" class="anchored" data-anchor-id="filtering-through-one-classification-and-aggregating-through-another"><span class="header-section-number">8.2.4.1</span> Filtering through one classification and aggregating through another</h4>
<p>ASFIS species may be represented under multiple classifications, such as:</p>
<ul>
<li>ISSCAAP;</li>
<li>TAXONOMIC.</li>
</ul>
<p>The app permits this workflow:</p>
<pre class="text"><code>Filter hierarchy: ISSCAAP
Aggregation hierarchy: TAXONOMIC</code></pre>
<p>Example:</p>
<ol type="1">
<li>Filter species belonging to ISSCAAP class <code>1501</code>.</li>
<li>In the aggregation tree, select a TAXONOMIC parent.</li>
<li>Aggregate the filtered raw species by the direct children of that TAXONOMIC parent.</li>
</ol>
<p>The aggregation tree is restricted to classifications containing at least one raw code remaining after filtering.</p>
</section>
<section id="direct-child-parent-selection-rule" class="level4" data-number="8.2.4.2">
<h4 data-number="8.2.4.2" class="anchored" data-anchor-id="direct-child-parent-selection-rule"><span class="header-section-number">8.2.4.2</span> Direct-child parent-selection rule</h4>
<p>The direct-child tree treats selected nodes as aggregation parents.</p>
<p>The effective parent selection uses the top, non-overlapping parent nodes.</p>
<p>When selecting <code>ISSCAAP</code>, descendants may appear checked because of the hierarchical tree behaviour, but <code>ISSCAAP</code> remains the effective parent and its direct children become the outputs.</p>
</section>
<section id="several-aggregation-parents" class="level4" data-number="8.2.4.3">
<h4 data-number="8.2.4.3" class="anchored" data-anchor-id="several-aggregation-parents"><span class="header-section-number">8.2.4.3</span> Several aggregation parents</h4>
<p>Several non-overlapping aggregation parents may be selected.</p>
<p>For example:</p>
<pre class="text"><code>Selected parents:
- 1501
- 1502
- 1503</code></pre>
<p>The outputs are the direct children of all three selected parents.</p>
<p>The selected parents must not overlap.</p>
</section>
<section id="parent-whose-children-are-leaves" class="level4" data-number="8.2.4.4">
<h4 data-number="8.2.4.4" class="anchored" data-anchor-id="parent-whose-children-are-leaves"><span class="header-section-number">8.2.4.4</span> Parent whose children are leaves</h4>
<p>Direct-child aggregation works when the selected parent has children even when those children have no descendants.</p>
<p>Example:</p>
<pre class="text"><code>MAJOR
├── Major fishing area A
├── Major fishing area B
└── Major fishing area C</code></pre>
<p>Selecting <code>MAJOR</code> produces:</p>
<pre class="text"><code>Major fishing area A
Major fishing area B
Major fishing area C</code></pre>
<p>The children do not need to have children of their own.</p>
</section>
<section id="selecting-a-leaf-as-the-aggregation-parent" class="level4" data-number="8.2.4.5">
<h4 data-number="8.2.4.5" class="anchored" data-anchor-id="selecting-a-leaf-as-the-aggregation-parent"><span class="header-section-number">8.2.4.5</span> Selecting a leaf as the aggregation parent</h4>
<p>A leaf cannot be used as a direct-child aggregation parent because it has no direct children.</p>
<pre class="text"><code>Selected aggregation parent: Species A
Result: error — no direct child groups</code></pre>
<p>This is different from selecting a leaf for <strong>Aggregate selected filter groups separately</strong>, where the leaf itself remains a valid output.</p>
</section>
<section id="overlapping-direct-child-outputs" class="level4" data-number="8.2.4.6">
<h4 data-number="8.2.4.6" class="anchored" data-anchor-id="overlapping-direct-child-outputs"><span class="header-section-number">8.2.4.6</span> Overlapping direct-child outputs</h4>
<p>Aggregation stops when:</p>
<ul>
<li>one output child belongs to more than one selected parent;</li>
<li>one raw code would be assigned to more than one direct-child output;</li>
<li>the selected classification itself contains overlapping direct-child branches.</li>
</ul>
<p>This validation prevents double counting.</p>
</section>
</section>
<section id="mode-5-custom-aggregation" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="mode-5-custom-aggregation"><span class="header-section-number">8.2.5</span> Mode 5: Custom aggregation</h3>
<p>Custom aggregation combines selected nodes and all their descendants into one output.</p>
<section id="output-naming" class="level4" data-number="8.2.5.1">
<h4 data-number="8.2.5.1" class="anchored" data-anchor-id="output-naming"><span class="header-section-number">8.2.5.1</span> Output naming</h4>
<ul>
<li>One selected node keeps its original code.</li>
<li>Several selected nodes within one dimension are combined into a single generated group, labelled <code>Custom Aggregation 1</code>. If custom aggregation is also applied to other dimensions in the same run, subsequent groups are labelled <code>Custom Aggregation 2</code>, <code>Custom Aggregation 3</code>, and so on.</li>
<li>Every filtered class not included in the custom group is combined into one dimension-specific <code>Other</code> output.</li>
</ul>
<p><strong>Example A: one selected node</strong></p>
<pre class="text"><code>Selected custom node: 1501

Outputs:
- 1501
- Other filtered species</code></pre>
<p>The <code>1501</code> output includes:</p>
<ul>
<li>1501 itself, when present as a raw data code;</li>
<li>every filtered descendant under 1501.</li>
</ul>
<p><strong>Example B: several selected nodes</strong></p>
<pre class="text"><code>Selected custom nodes:
- 1501
- 1502

Outputs:
- Custom Aggregation 1
- Other filtered species</code></pre>
<p><strong>Numerical example</strong></p>
<div class="cell">
<div id="tbl-custom-aggregation-example" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-custom-aggregation-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Illustrative custom aggregation
</figcaption>
<div aria-describedby="tbl-custom-aggregation-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">output_code</th>
<th style="text-align: left;">included_groups</th>
<th style="text-align: right;">aggregated_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Custom Aggregation 1</td>
<td style="text-align: left;">1501 + 1502</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other filtered species</td>
<td style="text-align: left;">1503</td>
<td style="text-align: right;">90</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="parent-and-descendant-selected-together" class="level4" data-number="8.2.5.2">
<h4 data-number="8.2.5.2" class="anchored" data-anchor-id="parent-and-descendant-selected-together"><span class="header-section-number">8.2.5.2</span> Parent and descendant selected together</h4>
<p>When both a parent and one of its descendants are selected for the same custom aggregation, only the parent is used as the effective selection, because the descendant is already included within the parent branch.</p>
<p>If only the descendant is selected, then the descendant itself is used as the custom aggregation group, together with any descendants below it.</p>
<p>When aggregation is applied to several dimensions, the final output reflects the combination of the selected aggregation settings; categories that remain separate in any retained dimension also remain separate in the output.</p>
</section>
</section>
</section>
</section>
<section id="filtering-and-aggregation-are-independent" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Filtering and aggregation are independent</h1>
<p>The filter tree and aggregation tree have different purposes.</p>
<div class="cell">
<div id="tbl-filter-aggregation-distinction" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-filter-aggregation-distinction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Distinction between filtering and aggregation selections
</figcaption>
<div aria-describedby="tbl-filter-aggregation-distinction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 27%">
<col style="width: 37%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Question_answered</th>
<th style="text-align: left;">Selection_rule</th>
<th style="text-align: left;">Expands_descendants</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Filter tree</td>
<td style="text-align: left;">Which filtered records remain?</td>
<td style="text-align: left;">Most-specific selected filter roots</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aggregation tree</td>
<td style="text-align: left;">How should the remaining records be grouped?</td>
<td style="text-align: left;">Top non-overlapping aggregation parents for direct-child mode</td>
<td style="text-align: left;">Yes, beneath each resulting output group</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="cross-classification-example" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="cross-classification-example"><span class="header-section-number">9.1</span> Cross-classification example</h2>
<p>Suppose the dataset contains five species.</p>
<div class="cell">
<div id="tbl-cross-classification" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cross-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: Illustrative cross-classification of species
</figcaption>
<div aria-describedby="tbl-cross-classification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">ISSCAAP</th>
<th style="text-align: left;">TAXONOMIC_family</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Species A</td>
<td style="text-align: left;">1501</td>
<td style="text-align: left;">Family X</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species B</td>
<td style="text-align: left;">1501</td>
<td style="text-align: left;">Family Y</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species C</td>
<td style="text-align: left;">1501</td>
<td style="text-align: left;">Family X</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species D</td>
<td style="text-align: left;">1502</td>
<td style="text-align: left;">Family Z</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species E</td>
<td style="text-align: left;">1502</td>
<td style="text-align: left;">Family Z</td>
<td style="text-align: right;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The user can:</p>
<ol type="1">
<li>filter through ISSCAAP and retain only <code>1501</code>;</li>
<li>aggregate through TAXONOMIC;</li>
<li>obtain <code>Family X</code> and <code>Family Y</code> outputs from the filtered records.</li>
</ol>
<div class="cell">
<div id="tbl-cross-classification-output" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cross-classification-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: Result of filtering through ISSCAAP 1501 and aggregating by TAXONOMIC family
</figcaption>
<div aria-describedby="tbl-cross-classification-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">TAXONOMIC_family</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Family X</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td style="text-align: left;">Family Y</td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="numerical-aggregation" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Numerical aggregation</h1>
<section id="value-calculation" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="value-calculation"><span class="header-section-number">10.1</span> Value calculation</h2>
<p>For every output group, the application calculates the numerical value directly from the mapped input records.</p>
<p>The aggregated value for group (g) is:</p>
<p><span class="math display">\[
V_g = \sum_{i \in g} V_i.
\]</span></p>
<p>The aggregated result is rounded to a maximum of four decimal places.</p>
</section>
</section>
<section id="flag-aggregation" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Flag aggregation</h1>
<p>Numerical values are aggregated according to the selected aggregation rule, while observation flags are aggregated according to the applicable FAO flag rules. The application uses <code>faoswsFlag::aggregateFlagData()</code> to calculate aggregate observation-status and method flags.</p>
<p>The function is called with:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>forceMissingAggregateValues <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>includeMissingFlags <span class="ot">=</span> <span class="cn">TRUE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The observation flag can first be filtered like the other filter dimensions. For example, the user may retain only <code>A</code> records, only <code>E</code> records, or several observation-flag categories.</p>
<p>When <strong>Aggregate separately by observation flag</strong> is selected, the observation-flag values remaining after filtering are kept separate during aggregation.</p>
<p>For example, if <code>A</code>, <code>E</code>, and <code>N</code> remain after filtering:</p>
<pre class="text"><code>A records are aggregated only with A records.
E records are aggregated only with E records.
N records are aggregated only with N records.</code></pre>
<p>The observation flag is preserved in the output.</p>
<p>If only <code>A</code> has been retained through the observation-flag filter, then only <code>A</code> records enter the aggregation.</p>
<p>When <strong>Aggregate separately by observation flag</strong> is not selected, records with different observation flags that remain after filtering may contribute to the same aggregated value, and the resulting aggregate flag is determined according to the FAO flag aggregation rules.</p>
</section>
<section id="year-aggregation" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Year aggregation</h1>
<p>By default, selected years remain separate in the output.</p>
<p>For example, if the selected period is 2015–2020 and the following values belong to the same combination of all other dimensions:</p>
<pre class="text"><code>Year    Value
2015     10
2016     12
2017     15
2018     11
2019     14
2020     18</code></pre>
<p>the output normally keeps six separate yearly records.</p>
<p>When <strong>Total all selected years into one period</strong> is selected, the years are combined into a single period and their values are aggregated:</p>
<pre class="text"><code>Period       Value
2015-2020     80</code></pre>
<p>because:</p>
<p><span class="math display">\[
10 + 12 + 15 + 11 + 14 + 18 = 80.
\]</span></p>
<p>The period label <code>2015-2020</code> therefore represents the aggregation of all selected years, not simply a relabelling of the individual annual records.</p>
<p>If other dimensions remain different, their records are still kept separate. Year aggregation combines records across the selected years only when they refer to the same species, fishing area, geographical area, production source, measured element, and any other dimensions that remain in the output.</p>
</section>
<section id="measured-element-processing" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Measured-element processing</h1>
<p>Measured elements are processed independently.</p>
<p>The workflow is:</p>
<ol type="1">
<li>apply year and dimension filters;</li>
<li>read selected measured elements;</li>
<li>create one subset per selected measured element;</li>
<li>run the same aggregation specifications on each subset;</li>
<li>save one output table per measured element.</li>
</ol>
<p><strong>Example</strong></p>
<pre class="text"><code>Selected measured elements:
- FI_001
- FI_002</code></pre>
<p>The Dataset table page contains:</p>
<pre class="text"><code>Tab FI_001
Tab FI_002</code></pre>
<p>The two elements are not summed together.</p>
<p>When a selected measured element has no rows after filtering, the application creates a warning tab for that measured element instead of terminating all other outputs.</p>
<p>Other selected measured elements may still be processed successfully.</p>
</section>
<section id="aggregation-output-tables" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Aggregation output tables</h1>
<p>The Dataset table page displays one tab per measured element.</p>
<p>Each successful tab contains a table with:</p>
<ul>
<li>column-level filtering;</li>
<li>horizontal scrolling;</li>
<li>a full-screen option;</li>
<li>a CSV download button.</li>
</ul>
<p>The downloaded CSV file is in long format. Each row represents one resulting combination of the dimensions retained in the aggregated output, with the aggregated numerical result reported in the Value column.</p>
<p>A separate CSV file can be downloaded for each measured element.</p>
<p>Warning tabs contain an explanation of why an output could not be created.</p>
</section>
<section id="graphs" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Graphs</h1>
<p>The <strong>Graphs</strong> page visualizes the results produced by the aggregation.</p>
<p>Graphs are displayed for <strong>one measured element at a time</strong>. If only one measured element was included in the aggregation, that measured element is shown automatically. If several measured elements were included, the user can select which output to visualize using the <strong>Measured element for graphs</strong> selector.</p>
<p>The page contains five graphical views:</p>
<ul>
<li><strong>Aggregated total</strong>;</li>
<li><strong>Stacked bar chart</strong>;</li>
<li><strong>Relative stacked bar chart</strong>;</li>
<li><strong>Component time series</strong>;</li>
<li><strong>Treemap chart</strong>.</li>
</ul>
<p>For all graphs except <strong>Aggregated total</strong>, the user also selects how the results should be categorized through the <strong>Categorize by</strong> selector.</p>
<section id="aggregated-total" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="aggregated-total"><span class="header-section-number">15.1</span> Aggregated total</h2>
<p>The <strong>Aggregated total</strong> view shows the total aggregated value for each year or aggregated period.</p>
<div id="fig-aggregated-total-graph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aggregated-total-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/aggregated_total_graph.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aggregated-total-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Aggregated total graph
</figcaption>
</figure>
</div>
<p>For every year or period displayed on the horizontal axis, the application sums all values in the selected measured-element output.</p>
<p>For example, suppose the selected output contains:</p>
<pre class="text"><code>Year    Category    Value
2020    A           30
2020    B           20
2020    C           50
2021    A           40
2021    B           25
2021    C           55</code></pre>
<p>The graph displays:</p>
<pre class="text"><code>2020    100
2021    120</code></pre>
<p>because:</p>
<p><span class="math display">\[
30 + 20 + 50 = 100
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
40 + 25 + 55 = 120.
\]</span></p>
<p>The graph therefore shows the overall total for the selected measured element rather than its composition by individual categories. The current implementation displays these totals as bars. If <strong>Total all selected years into one period</strong> was selected during aggregation, the aggregated period label, for example <code>2015-2020</code>, is displayed instead of separate annual values.</p>
</section>
<section id="categorize-by" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="categorize-by"><span class="header-section-number">15.2</span> Categorize by</h2>
<p>The remaining four graphs require the user to choose a category through the <strong>Categorize by</strong> selector.</p>
<p>Depending on the aggregation that was performed, the selector can contain two types of choices:</p>
<ul>
<li><strong>Aggregation composition</strong>;</li>
<li><strong>Final result column</strong>.</li>
</ul>
<section id="aggregation-composition" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="aggregation-composition"><span class="header-section-number">15.2.1</span> Aggregation composition</h3>
<p>An <strong>Aggregation composition</strong> option is available for dimensions that were aggregated.</p>
<p>For example, if species were aggregated using <strong>Aggregate by direct children of ISSCAAP</strong>, the graph can show the contribution of the resulting ISSCAAP groups.</p>
<p>The application uses the aggregation rule that produced the result to determine which records belong to each aggregation group. The graph then calculates the total value of each group for every year or period. For example:</p>
<pre class="text"><code>Year    ISSCAAP group    Value
2020    1501             40
2020    1502             60
2021    1501             45
2021    1502             75</code></pre>
<p>can be displayed as two components, <code>1501</code> and <code>1502</code>, in the stacked bar chart, relative stacked bar chart, component time series, or treemap.</p>
</section>
<section id="final-result-column" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="final-result-column"><span class="header-section-number">15.2.2</span> Final result column</h3>
<p>A <strong>Final result column</strong> uses one of the dimensions that remains in the final aggregated dataset.</p>
<p>This option categorizes the graph using a dimension that was not aggregated and therefore remains separate in the final output. Possible examples include:</p>
<ul>
<li>geographical area;</li>
<li>species;</li>
<li>fishing area;</li>
<li>observation flag;</li>
<li>production source;</li>
<li>currency flag, where available.</li>
</ul>
<p>Only columns containing at least two categories in the selected output are offered as categorization choices.</p>
<p>A dimension that has already been aggregated is not offered again as a <strong>Final result column</strong>. Instead, its composition can be examined through the corresponding <strong>Aggregation composition</strong> option.</p>
</section>
</section>
<section id="stacked-bar-chart" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="stacked-bar-chart"><span class="header-section-number">15.3</span> Stacked bar chart</h2>
<p>The <strong>Stacked bar chart</strong> shows the absolute value for each year or period, divided into the categories selected under <strong>Categorize by</strong>.</p>
<p>For example:</p>
<pre class="text"><code>Year    Category    Value
2020    A           30
2020    B           70
2021    A           40
2021    B           80</code></pre>
<p>produces one bar for 2020 and one bar for 2021.</p>
<p>The 2020 bar has a total height of <code>100</code>, divided into:</p>
<pre class="text"><code>A = 30
B = 70</code></pre>
<p>The 2021 bar has a total height of <code>120</code>, divided into:</p>
<pre class="text"><code>A = 40
B = 80</code></pre>
<p>The height of each complete bar therefore represents the total value for that year or period, while the coloured sections show how the selected categories contribute to that total.</p>
<div id="fig-stacked-bar-chart" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stacked-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/stacked_bar_chart.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stacked-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Stacked bar chart
</figcaption>
</figure>
</div>
</section>
<section id="relative-stacked-bar-chart" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="relative-stacked-bar-chart"><span class="header-section-number">15.4</span> Relative stacked bar chart</h2>
<p>The <strong>Relative stacked bar chart</strong> shows the same composition as the stacked bar chart, but expresses each category as a <strong>percentage of the total for that year or period</strong> rather than as an absolute value.</p>
<div id="fig-relative-stacked-bar-chart" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-relative-stacked-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/relative_stacked_bar_chart.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-relative-stacked-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Relative stacked bar chart
</figcaption>
</figure>
</div>
<p>For a year or period (t) and category (c), the share is calculated as:</p>
<p><span class="math display">\[
s_{ct} =
\frac{V_{ct}}
{\sum_c V_{ct}}.
\]</span></p>
<p>For example, if the values in 2020 are:</p>
<pre class="text"><code>Category A = 30
Category B = 70</code></pre>
<p>the total is:</p>
<p><span class="math display">\[
30 + 70 = 100.
\]</span></p>
<p>The relative stacked bar therefore displays:</p>
<pre class="text"><code>Category A = 30%
Category B = 70%</code></pre>
<p>If in 2021 the values are:</p>
<pre class="text"><code>Category A = 40
Category B = 80</code></pre>
<p>the total is <code>120</code>, so the shares are approximately:</p>
<pre class="text"><code>Category A = 33.3%
Category B = 66.7%</code></pre>
<p>Each complete bar represents 100%, which makes it possible to compare changes in composition over time even when the absolute totals differ substantially between years.</p>
</section>
<section id="component-time-series" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="component-time-series"><span class="header-section-number">15.5</span> Component time series</h2>
<p>The <strong>Component time series</strong> shows the evolution of each selected category over time.</p>
<div id="fig-component-time-series" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-component-time-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/component_time_series.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-component-time-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Component time series
</figcaption>
</figure>
</div>
<p>A separate line is drawn for every category selected through <strong>Categorize by</strong>, with points showing the value for each year or period.</p>
<p>For example:</p>
<pre class="text"><code>Year    Category A    Category B
2020       30            70
2021       40            80
2022       55            75</code></pre>
<p>produces one line for <strong>Category A</strong> and another for <strong>Category B</strong>.</p>
<p>This view is useful for examining how the individual components change over time rather than looking only at the overall total.</p>
<p>Depending on the selected categorization, the lines may represent, for example:</p>
<ul>
<li>geographical groups;</li>
<li>species groups;</li>
<li>fishing areas;</li>
<li>production sources;</li>
<li>observation-flag categories;</li>
<li>currency-flag categories;</li>
<li>another dimension remaining in the aggregated output.</li>
</ul>
</section>
<section id="treemap" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="treemap"><span class="header-section-number">15.6</span> Treemap</h2>
<p>The <strong>Treemap chart</strong> shows the composition of the selected measured-element output for <strong>one year or aggregated period at a time</strong>.</p>
<div id="fig-treemap-chart" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-treemap-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/treemap_chart.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-treemap-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Treemap chart
</figcaption>
</figure>
</div>
<p>The user selects the year or period using the <strong>Treemap year</strong> selector. By default, the most recent available year or period is selected.</p>
<p>Each rectangle represents one category from the selected <strong>Categorize by</strong> option.</p>
<p>The area of each rectangle is proportional to the total value of that category.</p>
<p>For example, if the selected period contains:</p>
<pre class="text"><code>Category A    50
Category B    30
Category C    20</code></pre>
<p>the treemap represents:</p>
<pre class="text"><code>Category A    50%
Category B    30%
Category C    20%</code></pre>
<p>The label displayed inside each tile contains:</p>
<ul>
<li>the category;</li>
<li>its percentage share of the total.</li>
</ul>
<p>Only categories with a positive, nonmissing total value are included in the treemap.</p>
<p>The treemap therefore provides a compact view of the relative importance of the different categories for one specific year or aggregated period.</p>
</section>
</section>
<section id="dataset-comparison" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> Dataset comparison</h1>
<section id="eligibility-and-required-sequence" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="eligibility-and-required-sequence"><span class="header-section-number">16.1</span> Eligibility and required sequence</h2>
<p>Comparison is available only when the main loaded dataset is a current Fisheries dataset.</p>
<p>A comparison source may be:</p>
<ul>
<li>a disseminated dataset;</li>
<li>a tagged version associated with a base Fisheries dataset.</li>
</ul>
<div id="fig-tagged-dataset-upload" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tagged-dataset-upload-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/tagged_dataset_upload.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tagged-dataset-upload-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Tagged dataset upload
</figcaption>
</figure>
</div>
<p>The intended workflow is:</p>
<ol type="1">
<li>load a current dataset;</li>
<li>select filters;</li>
<li>run aggregation;</li>
<li>open the Comparison page;</li>
<li>load a disseminated or tagged comparison dataset;</li>
<li>review compatibility warnings;</li>
<li>run comparison.</li>
</ol>
</section>
<section id="reuse-of-the-aggregation-state" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="reuse-of-the-aggregation-state"><span class="header-section-number">16.2</span> Reuse of the aggregation state</h2>
<p>The application stores:</p>
<ul>
<li>filtered input used for the current aggregation;</li>
<li>selected measured elements;</li>
<li>aggregation specifications;</li>
<li>year-aggregation choice;</li>
<li>observation-flag grouping choice;</li>
<li>filter state.</li>
</ul>
<p>The comparison dataset is processed using the same analytical setup.</p>
<p>Aggregation maps are rebuilt against the filtered comparison data so that the comparison follows the same requested hierarchy logic while accounting for codes present in the comparison source.</p>
</section>
<section id="matching-records-for-comparison" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="matching-records-for-comparison"><span class="header-section-number">16.3</span> Matching records for comparison</h2>
<p>To compare the current and comparison datasets, the application first identifies records that refer to the same combination of analytical dimensions.</p>
<p>Only dimensions available in both the current and comparison results are used.</p>
<p>For example, a current value for a particular year, geographical area, species and fishing area is compared with the value from the comparison dataset referring to the same combination of these categories.</p>
<p>If one of the relevant categories differs, the records are not treated as the same observation for comparison.</p>
<p>Observation flags are not used to match records because the current and comparison datasets may use different flag classifications.</p>
</section>
<section id="comparison-values" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="comparison-values"><span class="header-section-number">16.4</span> Comparison values</h2>
<p>For every matched analytical combination, the output contains:</p>
<ul>
<li><code>current_value</code>;</li>
<li><code>comparison_value</code>;</li>
<li><code>absolute_difference</code>;</li>
<li><code>percentage_difference</code>;</li>
<li><code>comparison_status</code>.</li>
</ul>
<p>The absolute difference is:</p>
<p><span class="math display">\[
    D = V_{\text{current}} - V_{\text{comparison}}.
\]</span></p>
<p>The percentage difference is:</p>
<p><span class="math display">\[
    P =
      100
    \frac{
      V_{\text{current}} - V_{\text{comparison}}
    }{
      V_{\text{comparison}}
    }.
\]</span></p>
<p>It is calculated only when the comparison value is nonzero.</p>
</section>
<section id="comparison-statuses" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="comparison-statuses"><span class="header-section-number">16.5</span> Comparison statuses</h2>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>comparison_statuses <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Status =</span> <span class="fu">c</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Same value"</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Different value"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Only in current output"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Only in comparison output"</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Meaning =</span> <span class="fu">c</span>(</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Both rows exist and their rounded values are equal"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Both rows exist but their values differ"</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"The analytical combination exists only in the current result"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"The analytical combination exists only in the comparison result"</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(comparison_statuses)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-comparison-statuses" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-statuses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15: Comparison status categories
</figcaption>
<div aria-describedby="tbl-comparison-statuses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 71%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Status</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Same value</td>
<td style="text-align: left;">Both rows exist and their rounded values are equal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Different value</td>
<td style="text-align: left;">Both rows exist but their values differ</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Only in current output</td>
<td style="text-align: left;">The analytical combination exists only in the current result</td>
</tr>
<tr class="even">
<td style="text-align: left;">Only in comparison output</td>
<td style="text-align: left;">The analytical combination exists only in the comparison result</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Numerical example</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>comparison_example <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">c</span>(<span class="st">"1501"</span>, <span class="st">"1502"</span>, <span class="st">"1503"</span>, <span class="st">"1504"</span>),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">current_value =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">80</span>, <span class="dv">50</span>, <span class="dv">40</span>),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison_value =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">80</span>, <span class="cn">NA</span>, <span class="dv">60</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>comparison_example<span class="sc">$</span>absolute_difference <span class="ot">&lt;-</span> <span class="fu">with</span>(</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  comparison_example,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  current_value <span class="sc">-</span> comparison_value</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>comparison_example<span class="sc">$</span>percentage_difference <span class="ot">&lt;-</span> <span class="fu">with</span>(</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  comparison_example,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span> <span class="sc">*</span> absolute_difference <span class="sc">/</span> comparison_value</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>comparison_example<span class="sc">$</span>status <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Different value"</span>,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Same value"</span>,</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Only in current output"</span>,</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Different value"</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(comparison_example)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-comparison-example" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-comparison-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16: Illustrative comparison output
</figcaption>
<div aria-describedby="tbl-comparison-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 21%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">current_value</th>
<th style="text-align: right;">comparison_value</th>
<th style="text-align: right;">absolute_difference</th>
<th style="text-align: right;">percentage_difference</th>
<th style="text-align: left;">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1501</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: left;">Different value</td>
</tr>
<tr class="even">
<td style="text-align: left;">1502</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: left;">Same value</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1503</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Only in current output</td>
</tr>
<tr class="even">
<td style="text-align: left;">1504</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">-20</td>
<td style="text-align: right;">-33.33</td>
<td style="text-align: left;">Different value</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="differences-in-category-coverage" class="level2" data-number="16.6">
<h2 data-number="16.6" class="anchored" data-anchor-id="differences-in-category-coverage"><span class="header-section-number">16.6</span> Differences in category coverage</h2>
<p>After applying the filters, the application checks whether the current and comparison datasets contain the same categories for the dimensions that were aggregated.</p>
<p>For example, suppose the species categories remaining in the two datasets are:</p>
<pre class="text"><code>Current dataset:      1501, 1502
Comparison dataset:   1501, 1503</code></pre>
<p>In this case:</p>
<ul>
<li><code>1501</code> is present in both datasets;</li>
<li><code>1502</code> is present only in the current dataset;</li>
<li><code>1503</code> is present only in the comparison dataset.</li>
</ul>
<p>The application displays a warning identifying these differences. It also indicates how many of the categories found only in one dataset have at least one non-missing numerical value.</p>
<p>This helps the user identify situations in which the two datasets do not have exactly the same category coverage after filtering.</p>
<p>The warning does not stop the comparison. The same filters and aggregation rules are still applied, and the comparison continues.</p>
</section>
<section id="comparison-outputs" class="level2" data-number="16.7">
<h2 data-number="16.7" class="anchored" data-anchor-id="comparison-outputs"><span class="header-section-number">16.7</span> Comparison outputs</h2>
<p>Two views are available:</p>
<ul>
<li><strong>All comparison rows</strong></li>
<li><strong>Differences only</strong></li>
</ul>
<div id="fig-all-comparison-rows" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-all-comparison-rows-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/all_comparison_rows.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-all-comparison-rows-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: All comparison rows
</figcaption>
</figure>
</div>
<div id="fig-differences-only-table" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-differences-only-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/differences_only_no_differences.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-differences-only-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Differences only table
</figcaption>
</figure>
</div>
<p>Each measured element has its own comparison tab and CSV download.</p>
</section>
</section>
<section id="outlier-analysis" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Outlier analysis</h1>
<p>The <strong>Outlier analysis</strong> page provides tools for examining unusually large aggregated values and unusually large changes over time.</p>
<p>The analysis is based on the <strong>aggregation output produced on the Filters &amp; Aggregation page</strong>. It does not operate directly on the original loaded dataset. Therefore, an aggregation must first be run before the outlier analysis can be used.</p>
<p>The page contains two views:</p>
<ul>
<li><strong>Distribution by year</strong>;</li>
<li><strong>Largest / strongest records</strong>.</li>
</ul>
<p>The same selections made in the sidebar are applied to both views.</p>
<section id="measured-element-for-outlier-analysis" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="measured-element-for-outlier-analysis"><span class="header-section-number">17.1</span> Measured element for outlier analysis</h2>
<p>Outlier analysis is performed for one measured element at a time.</p>
<p>If the aggregation produced only one measured-element output, that measured element is used automatically.</p>
<p>If several measured elements were aggregated, the <strong>Measured element for outlier analysis</strong> selector allows the user to choose which output to examine.</p>
<p>For example, if separate aggregation outputs were produced for quantity and value, the outlier analysis is performed on only one of these outputs at a time.</p>
</section>
<section id="analyse-outliers-for" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="analyse-outliers-for"><span class="header-section-number">17.2</span> Analyse outliers for</h2>
<p>The <strong>Analyse outliers for</strong> selector determines whether the analysis is carried out on the entire selected aggregation output or restricted to one particular group.</p>
<p>The default option is:</p>
<pre class="text"><code>Full selected aggregation output</code></pre>
<p>In this case, all records from the selected measured-element output are included in the analysis.</p>
<p>The selector can also contain columns available in the selected aggregation output, for example:</p>
<ul>
<li><code>geographicAreaM49_fi</code>;</li>
<li><code>fisheriesAsfis</code>;</li>
<li><code>fisheriesCatchArea</code>;</li>
<li><code>measuredElement</code>;</li>
<li><code>flagObservationStatus</code>;</li>
<li><code>fisheriesProductionSource</code>, where available;</li>
<li><code>flagCurrency</code>, where available.</li>
</ul>
<p>The available choices depend on the structure of the selected dataset and on the aggregation that was performed. When one of these columns is selected, an additional <strong>Selected group value</strong> selector appears. This allows the analysis to be restricted to one specific category from that column.</p>
<p>For example:</p>
<pre class="text"><code>Analyse outliers for: fisheriesAsfis
Selected group value: 1501</code></pre>
<p>restricts the analysis to records belonging to species group <code>1501</code>.</p>
<p>Similarly:</p>
<pre class="text"><code>Analyse outliers for: geographicAreaM49_fi
Selected group value: 380</code></pre>
<p>restricts the analysis to the selected geographical category.</p>
<p>This option is useful when values from very different groups should not be examined together. For example, instead of comparing the distribution across all geographical areas, the user can examine the observations belonging to one geographical area only.</p>
</section>
<section id="outlier-metric" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="outlier-metric"><span class="header-section-number">17.3</span> Outlier metric</h2>
<p>The <strong>Outlier metric</strong> selector determines which quantity is examined.</p>
<p>The <strong>Value</strong> metric is always available.</p>
<p>When the selected measured-element output contains at least two periods, two additional metrics are available:</p>
<ul>
<li><strong>Year-on-year absolute change</strong>;</li>
<li><strong>Year-on-year percentage change</strong>.</li>
</ul>
<p>There is no test that the periods are consecutive. So if a series has:</p>
<pre class="text"><code>2018
2019
2022</code></pre>
<p>the 2022 change will be calculated against 2019 and called year-on-year, even though it is a three-year gap.</p>
<p>If the aggregation has combined all selected years into a single period, the change metrics are not available because there is no earlier period with which to calculate a change.</p>
<section id="value" class="level3" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="value"><span class="header-section-number">17.3.1</span> Value</h3>
<p>With <strong>Value</strong> selected, the analysis uses the aggregated <code>Value</code> directly.</p>
<div id="fig-value-outlier-metric" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-value-outlier-metric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/distribution_by_year_asfis.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-value-outlier-metric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Value outlier metric
</figcaption>
</figure>
</div>
<p>For example, suppose the selected aggregation output contains:</p>
<pre class="text"><code>Year    Geographical area    Species    Value
2020    380                  1501       120
2020    250                  1501        80
2020    724                  1501       200</code></pre>
<p>The values analysed are <code>120</code>, <code>80</code> and <code>200</code>.</p>
<p>A large value is not automatically treated as an error. It may simply correspond to a genuinely large geographical area, species group, fishing area or other category.</p>
<p>The <strong>Value</strong> metric should therefore be interpreted as a screening tool for identifying records that may deserve further examination.</p>
</section>
<section id="year-on-year-absolute-change" class="level3" data-number="17.3.2">
<h3 data-number="17.3.2" class="anchored" data-anchor-id="year-on-year-absolute-change"><span class="header-section-number">17.3.2</span> Year-on-year absolute change</h3>
<p>The <strong>Year-on-year absolute change</strong> metric examines how much a value changes from the previous available period for the same series.</p>
<div id="fig-year-on-year-metric" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year-on-year-metric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/largest_records_absolute_change.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-year-on-year-metric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Year-on-year absolute change selector
</figcaption>
</figure>
</div>
<p>It is calculated as:</p>
<p><span class="math display">\[
\Delta_t = V_t - V_{\mathrm{prev}}.
\]</span></p>
<p>For example, suppose the same geographical area, species and fishing area has:</p>
<pre class="text"><code>Year    Value
2020    100
2021    135</code></pre>
<p>The absolute change for 2021 is:</p>
<p><span class="math display">\[
135 - 100 = 35.
\]</span></p>
<p>A positive value represents an increase and a negative value represents a decrease.</p>
<p>For example:</p>
<pre class="text"><code>2020    100
2021     70</code></pre>
<p>produces:</p>
<p><span class="math display">\[
70 - 100 = -30.
\]</span></p>
<p>The first available period for each series has no previous value and therefore cannot have an absolute-change value.</p>
<p>The resulting change is expressed in the same unit as the selected measured element. For example, if the measured element is expressed in tonnes, the absolute change is also expressed in tonnes.</p>
</section>
<section id="year-on-year-percentage-change" class="level3" data-number="17.3.3">
<h3 data-number="17.3.3" class="anchored" data-anchor-id="year-on-year-percentage-change"><span class="header-section-number">17.3.3</span> Year-on-year percentage change</h3>
<p>The <strong>Year-on-year percentage change</strong> metric expresses the change relative to the magnitude of the previous available value.</p>
<p>It is calculated as:</p>
<p><span class="math display">\[
\%\Delta_t =
100 \times
\frac{V_t - V_{\mathrm{prev}}}
{|V_{\mathrm{prev}}|}.
\]</span></p>
<p>For example:</p>
<pre class="text"><code>Previous value: 100
Current value: 150</code></pre>
<p>gives:</p>
<p><span class="math display">\[
100 \times
\frac{150 - 100}{100}
=
50\%.
\]</span></p>
<p>A decrease from <code>100</code> to <code>70</code> gives:</p>
<p><span class="math display">\[
100 \times
\frac{70 - 100}{100}
=
-30\%.
\]</span></p>
<p>The percentage change is not calculated when the previous value is zero, because division by zero is not possible.</p>
<p>Percentage changes should also be interpreted carefully when the previous value is very small. For example, an increase from <code>1</code> to <code>10</code> produces a very large percentage change even though the absolute change is only <code>9</code>.</p>
</section>
</section>
<section id="distribution-by-year" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="distribution-by-year"><span class="header-section-number">17.4</span> Distribution by year</h2>
<p>The <strong>Distribution by year</strong> tab provides a graphical view of the selected metric across the available years or periods.</p>
<p>For every year or period, the graph displays:</p>
<ul>
<li>a boxplot summarizing the distribution;</li>
<li>the individual records as jittered points.</li>
</ul>
<p>The horizontal axis represents the year or period and the vertical axis represents the selected outlier metric.</p>
<p>When <strong>Value</strong> is selected, each point represents the aggregated value of one record in the selected aggregation output.</p>
<p>For example, if the selected output contains many combinations of geographical areas, species and fishing areas for 2020, their values appear as individual points in the 2020 distribution.</p>
<p>When <strong>Year-on-year absolute change</strong> is selected, each point represents the change from the previous available period.</p>
<p>When <strong>Year-on-year percentage change</strong> is selected, each point represents the corresponding percentage change.</p>
<p>The boxplot provides a summary of the distribution and helps identify values that are far from the majority of records. However, the application does not automatically classify these observations as errors or invalid data.</p>
<p>The plot therefore supports exploratory screening rather than automatic outlier detection.</p>
<p>If the analysis has been restricted using <strong>Analyse outliers for</strong> and <strong>Selected group value</strong>, the distribution is calculated only for that selected group.</p>
<p>The plot can also be opened using the full-screen option.</p>
</section>
<section id="largest-strongest-records" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="largest-strongest-records"><span class="header-section-number">17.5</span> Largest / strongest records</h2>
<p>The <strong>Largest / strongest records</strong> tab provides a table of the observations with the largest values or strongest changes.</p>
<p>The way records are ranked depends on the selected metric.</p>
<section id="value-1" class="level3" data-number="17.5.1">
<h3 data-number="17.5.1" class="anchored" data-anchor-id="value-1"><span class="header-section-number">17.5.1</span> Value</h3>
<p>When <strong>Value</strong> is selected, records are ordered from the highest aggregated value to the lowest.</p>
<p>For example:</p>
<pre class="text"><code>Value
500
350
220
100</code></pre>
<p>would be displayed starting with <code>500</code>.</p>
<p>This view helps identify which combinations of year, geographical area, species, fishing area and other dimensions generate the largest aggregated values.</p>
</section>
<section id="year-on-year-absolute-change-1" class="level3" data-number="17.5.2">
<h3 data-number="17.5.2" class="anchored" data-anchor-id="year-on-year-absolute-change-1"><span class="header-section-number">17.5.2</span> Year-on-year absolute change</h3>
<p>When <strong>Year-on-year absolute change</strong> is selected, records are ordered according to the <strong>absolute magnitude of the change</strong>.</p>
<div id="fig-largest-records-data" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-largest-records-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/largest_records_data.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-largest-records-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Largest records table
</figcaption>
</figure>
</div>
<p>This means that both large increases and large decreases can appear at the top of the table.</p>
<p>For example:</p>
<pre class="text"><code>Change
+500
-450
+300
-250</code></pre>
<p>is ranked according to the size of the change, regardless of its direction.</p>
<p>The table includes the current <code>Value</code>, the <code>previous_value</code> used for the calculation and the calculated change.</p>
</section>
<section id="year-on-year-percentage-change-1" class="level3" data-number="17.5.3">
<h3 data-number="17.5.3" class="anchored" data-anchor-id="year-on-year-percentage-change-1"><span class="header-section-number">17.5.3</span> Year-on-year percentage change</h3>
<p>The same ranking principle is used for <strong>Year-on-year percentage change</strong>.</p>
<p>For example:</p>
<pre class="text"><code>Percentage change
+250%
-200%
+150%
-120%</code></pre>
<p>is ordered according to the absolute size of the percentage change.</p>
<p>Both unusually large increases and unusually large decreases are therefore highlighted.</p>
<p>The current <code>Value</code> and the <code>previous_value</code> are retained in the table so that the percentage change can be interpreted together with the underlying numerical values.</p>
<p>This is particularly important when very large percentages are generated by a small previous value.</p>
</section>
</section>
<section id="number-of-top-records-to-display" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="number-of-top-records-to-display"><span class="header-section-number">17.6</span> Number of top records to display</h2>
<p>The <strong>Number of top records to display</strong> control appears when the <strong>Largest / strongest records</strong> tab is selected. The user can choose to display between <strong>10 and 200 records</strong>, in increments of 10. The default is <strong>50 records</strong>.</p>
<p>For the <strong>Value</strong> metric, these are the records with the largest values.</p>
<p>For the two change metrics, these are the records with the largest absolute changes, regardless of whether the change is positive or negative.</p>
</section>
<section id="download-outlier-csv" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="download-outlier-csv"><span class="header-section-number">17.7</span> Download outlier CSV</h2>
<p>The table shown in the <strong>Largest / strongest records</strong> tab can be downloaded using the <strong>Download outlier CSV</strong> button.</p>
<p>The downloaded CSV corresponds to:</p>
<ul>
<li>the selected measured element;</li>
<li>the selected analysis group, if one was specified;</li>
<li>the selected outlier metric;</li>
<li>the selected number of top records.</li>
</ul>
<p>The downloaded table contains the same relevant analytical columns used to identify the records displayed in the application. For change metrics, it also contains the previous value and the calculated change information required to interpret the result.</p>
</section>
</section>
<section id="worked-user-scenarios" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Worked user scenarios</h1>
<p>The following examples illustrate some typical ways in which filtering and aggregation can be combined in the application.</p>
<section id="scenario-1-filter-one-isscaap-group-keep-species-separate-and-aggregate-geographical-areas" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="scenario-1-filter-one-isscaap-group-keep-species-separate-and-aggregate-geographical-areas"><span class="header-section-number">18.1</span> Scenario 1: Filter one ISSCAAP group, keep species separate and aggregate geographical areas</h2>
<p><strong>Objective:</strong> restrict the data to species belonging to one ISSCAAP group, keep the individual species separate, and combine the selected geographical areas into one output.</p>
<p><strong>Procedure:</strong></p>
<ol type="1">
<li>Select the required years and measured element.</li>
<li>Select the required geographical areas in the geographical-area filter.</li>
<li>Set <strong>Geographical area aggregation</strong> to <strong>Combine all filtered values into one output</strong>.</li>
<li>In the species filter, select ISSCAAP group <code>1501</code>.</li>
<li>Set <strong>Species aggregation</strong> to <strong>Keep filtered codes separate</strong>.</li>
<li>Run the aggregation.</li>
</ol>
<p>Selecting <code>1501</code> in the species filter retains the species belonging to that ISSCAAP branch.</p>
<p>Because <strong>Keep filtered codes separate</strong> is selected for species, the individual species remain separate in the output. For example, if the filtered branch contains:</p>
<pre class="text"><code>Species A
Species B
Species C</code></pre>
<p>these species remain separate rather than being combined into a single <code>1501</code> result.</p>
<p>At the same time, the selected geographical areas are combined according to the geographical-area aggregation setting.</p>
<p>The final output therefore contains separate results for the individual species within <code>1501</code>, while the selected geographical areas are aggregated.</p>
</section>
<section id="scenario-2-aggregate-species-by-the-direct-isscaap-groups" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="scenario-2-aggregate-species-by-the-direct-isscaap-groups"><span class="header-section-number">18.2</span> Scenario 2: Aggregate species by the direct ISSCAAP groups</h2>
<p><strong>Objective:</strong> produce separate aggregated results for the direct groups under <code>ISSCAAP</code>.</p>
<p><strong>Procedure:</strong></p>
<ol type="1">
<li>Filter the species broadly enough to include the species required for the analysis.</li>
<li>Set <strong>Species aggregation</strong> to <strong>Aggregate by direct children</strong>.</li>
<li>In the aggregation hierarchy, select <code>ISSCAAP</code>.</li>
<li>Run the aggregation.</li>
</ol>
<p>If the hierarchy is:</p>
<pre class="text"><code>ISSCAAP
├── 1501
├── 1502
└── 1503</code></pre>
<p>the result contains separate outputs for:</p>
<pre class="text"><code>1501
1502
1503</code></pre>
<p>Each output includes the species belonging to that direct-child branch.</p>
<p>The application therefore does <strong>not</strong> create one single <code>ISSCAAP</code> total. Instead, the selected parent determines the level immediately below it that is used for the aggregation.</p>
</section>
<section id="scenario-3-filter-species-using-isscaap-and-aggregate-them-using-taxonomic" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="scenario-3-filter-species-using-isscaap-and-aggregate-them-using-taxonomic"><span class="header-section-number">18.3</span> Scenario 3: Filter species using ISSCAAP and aggregate them using TAXONOMIC</h2>
<p><strong>Objective:</strong> select species through one classification and summarize the selected species through another classification.</p>
<p>Suppose the user first restricts the data to species belonging to ISSCAAP group <code>1501</code>, but then wants to examine those species according to their taxonomic groups.</p>
<p><strong>Procedure:</strong></p>
<ol type="1">
<li>In the species filter, select ISSCAAP group <code>1501</code>.</li>
<li>Set <strong>Species aggregation</strong> to <strong>Aggregate by direct children</strong>.</li>
<li>In the aggregation hierarchy, open <code>TAXONOMIC</code>.</li>
<li>Select the required taxonomic parent.</li>
<li>Run the aggregation.</li>
</ol>
<p>For example, assume the filtered data contain:</p>
<pre class="text"><code>Species A    ISSCAAP 1501    Family X    10
Species B    ISSCAAP 1501    Family Y    20
Species C    ISSCAAP 1501    Family X    30
Species D    ISSCAAP 1502    Family Z    40</code></pre>
<p>Because the filter selected only ISSCAAP <code>1501</code>, Species D is excluded.</p>
<p>If the aggregation is then performed by taxonomic family, the result is:</p>
<pre class="text"><code>Family X    40
Family Y    20</code></pre>
<p>This illustrates that the hierarchy used for <strong>filtering</strong> does not have to be the same hierarchy used for <strong>aggregation</strong>.</p>
</section>
<section id="scenario-4-apply-different-aggregation-rules-to-several-dimensions" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="scenario-4-apply-different-aggregation-rules-to-several-dimensions"><span class="header-section-number">18.4</span> Scenario 4: Apply different aggregation rules to several dimensions</h2>
<p><strong>Objective:</strong> combine several aggregation settings in the same run.</p>
<p>Suppose the user wants to:</p>
<ul>
<li>combine the selected geographical areas into one geographical result;</li>
<li>aggregate species by the direct children of <code>ISSCAAP</code>;</li>
<li>keep fishing areas separate;</li>
<li>combine all selected years into one period.</li>
</ul>
<p>The settings could be:</p>
<pre class="text"><code>Geographical area:
Combine all filtered values into one output

Species:
Aggregate by direct children
Selected parent: ISSCAAP

Fishing area:
Keep filtered codes separate

Years:
Total all selected years into one period</code></pre>
<p>If the selected years are 2015–2020, the final output contains the period:</p>
<pre class="text"><code>2015-2020</code></pre>
<p>Within that period, separate rows are produced for each resulting combination of:</p>
<ul>
<li>the geographical-area aggregation output;</li>
<li>the direct ISSCAAP child;</li>
<li>the fishing area retained separately;</li>
<li>the measured element;</li>
<li>any other dimensions that remain separate.</li>
</ul>
<p>For example:</p>
<pre class="text"><code>Period       Geographical output    Species group    Fishing area    Value
2015-2020    TOTAL                  1501             Area 27         ...
2015-2020    TOTAL                  1501             Area 37         ...
2015-2020    TOTAL                  1502             Area 27         ...
2015-2020    TOTAL                  1502             Area 37         ...</code></pre>
<p>This scenario shows how the final result is determined by the <strong>combination of all aggregation settings</strong>, rather than by one dimension at a time.</p>
</section>
</section>
<section id="validation-and-error-handling" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> Validation and error handling</h1>
<p>Before and during aggregation, the application performs a number of checks to prevent incomplete or ambiguous results.</p>
<section id="dataset-and-aggregation-checks" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="dataset-and-aggregation-checks"><span class="header-section-number">19.1</span> Dataset and aggregation checks</h2>
<p>The application checks that:</p>
<ul>
<li>a dataset has been loaded and selected;</li>
<li>the dataset contains the columns required for the selected operation;</li>
<li>at least one measured element has been selected;</li>
<li>records remain after applying the selected year range and filters;</li>
<li>at least one aggregation operation has been selected, either for an aggregation dimension, for the selected years, or separately by observation flag.</li>
</ul>
<p>If no records remain after filtering, the aggregation is not run.</p>
<p>If a selected measured element has no records after applying the year range and dimension filters, no aggregation is produced for that measured element and a warning is shown instead.</p>
</section>
<section id="hierarchy-and-aggregation-checks" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="hierarchy-and-aggregation-checks"><span class="header-section-number">19.2</span> Hierarchy and aggregation checks</h2>
<p>For hierarchy-based aggregation, the application checks that:</p>
<ul>
<li>the required hierarchy selection has been made;</li>
<li>a parent selected for <strong>Aggregate by direct children</strong> has direct child groups;</li>
<li>selected hierarchy parents do not produce overlapping aggregation groups;</li>
<li>the same filtered category is not assigned to more than one output group;</li>
<li>every filtered category is assigned to an aggregation output;</li>
<li>for <strong>Custom aggregation</strong>, at least one selected hierarchy node corresponds to categories present in the filtered data.</li>
</ul>
<p>If any of these conditions would make the aggregation ambiguous or cause filtered records to be omitted, the aggregation is stopped and an error message is displayed.</p>
</section>
<section id="aggregation-error-diagnostics" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="aggregation-error-diagnostics"><span class="header-section-number">19.3</span> Aggregation error diagnostics</h2>
<p>When an error occurs during aggregation, the application adds information identifying the aggregation setting in which the error occurred.</p>
<p>Depending on the operation, the error message may include:</p>
<ul>
<li>the aggregation dimension, such as <strong>Species / ASFIS</strong> or <strong>Fishing area</strong>;</li>
<li>the corresponding dataset column;</li>
<li>the codelist used for the hierarchy;</li>
<li>the category or categories selected for aggregation;</li>
<li>the stage of the aggregation process in which the error occurred;</li>
<li>the specific error that caused the aggregation to stop.</li>
</ul>
<p>For example, if an error occurs while creating direct-child groups for a selected species hierarchy, the message identifies the species aggregation and the selected hierarchy parent before reporting the specific problem.</p>
<p>This additional information is intended mainly for debugging and maintenance, as it makes it possible to identify which aggregation setting caused the failure.</p>
</section>
<section id="per-measured-element-warnings" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="per-measured-element-warnings"><span class="header-section-number">19.4</span> Per-measured-element warnings</h2>
<p>An error affecting one measured element may produce a warning tab for that element while other measured elements continue processing.</p>
</section>
</section>
<section id="current-implementation-constraints" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Current implementation constraints</h1>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Quantity, value and price currently use the same summation logic
</div>
</div>
<div class="callout-body-container callout-body">
<p>The current implementation aggregates the <code>Value</code> column by summation for quantity, value and price datasets.</p>
<p>A quantity-weighted average for unit-price datasets is not currently applied.</p>
<p>Price-output interpretation must therefore account for this implementation rule.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Filter-only execution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The current Run handler requires at least one aggregation specification, year aggregation or observation-flag aggregation.</p>
<p>A run in which every dimension is set to <strong>Keep filtered codes separate</strong>, with no other aggregation option selected, is currently rejected.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Comparison direction
</div>
</div>
<div class="callout-body-container callout-body">
<p>A current dataset must be the main dataset.</p>
<p>A disseminated or tagged dataset is used as the comparison side.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Direct-child overlap
</div>
</div>
<div class="callout-body-container callout-body">
<p>When hierarchy definitions assign one code to more than one direct child, the application stops rather than duplicating and double-counting the record.</p>
</div>
</div>
</section>
<section id="main-functions-in-the-application" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> Main functions in the application</h1>
<div class="cell">
<div id="tbl-technical-functions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-technical-functions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17: Main functions in the application
</figcaption>
<div aria-describedby="tbl-technical-functions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Responsibility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">normalise_and_drop_empty_values()</td>
<td style="text-align: left;">Standardize the Value column, convert it to numeric and remove rows without a valid numerical value</td>
</tr>
<tr class="even">
<td style="text-align: left;">validate_dataset_columns()</td>
<td style="text-align: left;">Check that the dataset contains the required columns and identify missing optional columns</td>
</tr>
<tr class="odd">
<td style="text-align: left;">get_selected_codes_from_tree()</td>
<td style="text-align: left;">Interpret tree selections, apply the hierarchy selection rule and, where required, include descendants</td>
</tr>
<tr class="even">
<td style="text-align: left;">get_current_filtered_data()</td>
<td style="text-align: left;">Apply the active year and dimension filters to the selected dataset</td>
</tr>
<tr class="odd">
<td style="text-align: left;">build_selected_groups_map_with_remainder()</td>
<td style="text-align: left;">Create separate outputs for the selected filter groups and assign the remaining categories to Other</td>
</tr>
<tr class="even">
<td style="text-align: left;">build_classification_map_with_remainder()</td>
<td style="text-align: left;">Create outputs for the direct children of the selected hierarchy parents and assign the remaining categories to Other</td>
</tr>
<tr class="odd">
<td style="text-align: left;">build_custom_map_with_remainder()</td>
<td style="text-align: left;">Create one custom aggregation output and assign the remaining categories to Other</td>
</tr>
<tr class="even">
<td style="text-align: left;">aggregate_by_codelist()</td>
<td style="text-align: left;">Aggregate one dimension by summing values according to the aggregation mapping and calculating aggregate flags</td>
</tr>
<tr class="odd">
<td style="text-align: left;">aggregate_by_multiple_dimensions()</td>
<td style="text-align: left;">Apply the selected aggregation settings across dimensions and optionally aggregate years or preserve observation-flag groups</td>
</tr>
<tr class="even">
<td style="text-align: left;">build_comparison_result_table()</td>
<td style="text-align: left;">Match current and comparison results, calculate differences and assign comparison statuses</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prepare_outlier_data()</td>
<td style="text-align: left;">Prepare Value, absolute-change or percentage-change metrics for outlier analysis</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="maintenance-guidance-trigger-link-and-repository" class="level1" data-number="22">
<h1 data-number="22"><span class="header-section-number">22</span> Maintenance guidance, trigger link and repository</h1>
<p>The documentation should be revised whenever any of the following changes:</p>
<ul>
<li><code>DATASET_CONFIG</code>;</li>
<li>common dataset columns;</li>
<li>aggregation dimensions;</li>
<li>filter dimensions;</li>
<li>hierarchy-root treatment;</li>
<li>aggregation-mode semantics;</li>
<li>flag-aggregation rules;</li>
<li>comparison formulas;</li>
<li>outlier formulas;</li>
<li>graph types;</li>
<li>output download structure;</li>
<li>page navigation.</li>
</ul>
<p>A recommended version-control workflow is:</p>
<ol type="1">
<li>update the Shiny code;</li>
<li>test the modified behaviour;</li>
<li>revise this <code>.qmd</code> document;</li>
<li>render the HTML documentation;</li>
<li>review the rendered document;</li>
<li>commit both source code and documentation source;</li>
<li>publish or share the rendered HTML where appropriate.</li>
</ol>
<p>The trigger link for this Shiny Application:<br>
<a href="https://sws.qa.fao.org/tasks/trigger/a12c26d0-6297-4bd5-a26c-82909115b124">Open the Shiny Application</a></p>
<p>The GitHub repository:<br>
<a href="https://github.com/un-fao/sws-stat-fisheries-aggregation">Open the GitHub repository</a></p>
</section>
<section id="conclusion" class="level1" data-number="23">
<h1 data-number="23"><span class="header-section-number">23</span> Conclusion</h1>
<p>The Fisheries Aggregation Shiny App provides a flexible workflow for selecting, aggregating, comparing and analysing Fisheries data.</p>
<p>A key feature of the application is the separation between <strong>filtering</strong> and <strong>aggregation</strong>. Filters determine which data are included in the analysis, while aggregation settings determine how the selected data are grouped in the final output. This makes it possible, for example, to select data through one hierarchy and aggregate them through another.</p>
<p>Hierarchical filters and aggregation rules can be applied independently across several dimensions, including geographical area, species, fishing area and production source. Measured elements are processed separately, while year and observation-flag aggregation can be applied when required.</p>
<p>The resulting aggregated outputs can then be explored through tables and graphs, compared with alternative dataset versions, and examined through the outlier-analysis tools.</p>
<p>Overall, the application is designed to provide a consistent and transparent way to move from detailed Fisheries data to user-defined aggregated results while preserving the structure needed for subsequent analysis and comparison.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="fisheries_documentation_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>